---
title: "【文献】盛山和夫 (2013)「モダニティのあとの社会学の課題」"
author: "yaaruga"
date: "2024-04-11"
categories: [Imput]
draft: true
---
盛山和夫，2013，「モダニティのあとの社会学の課題――グローバリゼーションにおける可能性」宮島喬・舩橋晴俊・友枝敏雄・遠藤薫編『グローバリゼーションと社会学――モダニティ・グローバリティ・社会的公正』ミネルヴァ書房，188–204．

グローバリゼーションという論題との関係で社会学問の学問的現状を診断した論考。

筆者は社会学が「学問としての危機に直面している」と指摘したうえで、危機を3つの側面から論じている（189ff）。

1. 社会学の教科書のなかで社会学の定義が提示されていない。すなわち、社会現象や社会生活を対象とする科学であるという定義にとどまっている。

2. 社会学に固有の理論や概念や命題が共有財産として継承・共有されていない。かわりに、多様な具体的で多様な社会的現実を対象とするという特徴づけが強調される。

3. 学問の境界には必ずしも拘束されない研究領域が主題別に形成され、社会学への帰属意識が減衰している。

筆者によると、学際的な研究領域の形成自体は望ましい動向である反面、そうした主題的な研究領域（エスニシティ、ジェンダー、都市、福祉、開発など）は概して社会学との結びつきが稀薄である。それゆえに、研究の理論や概念が社会学とは必ずしも関連づけられず、その成果が社会学に還元されない、人的ネットワークもその領域に内閉する傾向がある、といった問題点があげられている（191ff）。

学部生のときに読んだときはさっぱり理解できなかったが、今読むとおおむね頷ける内容である。ただし筆者があげている3つのうちの1つめ・2つめの批判にはやや疑問が残る。一般に教科書は予備知識の少ない読者を当該分野へと導くことを目的とするのだから、その価値はその効果がどの程度生じているかという観点から評価されるべきだろう。社会学が魅力的に見えるとしたらそれはどのようなものとしてなのかは決して自明ではないし、多様な具体的で多様な社会的現実を対象とするという特徴づけが訴求力をもつならそれはそれで正当化できるだろう。

そのうえで3つめの問題提起はやはり特に重要であると思う。社会学が方法的に多様化してmulti-paradigmになっているという診断はすでに半世紀以上も前から多くなされているけれど、論題もまた多様化していて、それが方法論的・理論的統合と累積を阻害している、というわけだ。disciplineよりもtopicが境界の組織原理として重要であるという事態は、特にジェンダーやエスニシティに関して顕著であろう。ただしA. Abottが論じるようにこれは学問の発展に付随する構造的かつ一般的な問題でもあるので[^Abbott, Andrew Delano. 2001. *Chaos of Disciplines*. Chicago: University of Chicago Press.]、ここで筆者が論じているよりも広い視点で見たほうがいいのではないかという気もする。