---
title: "社会(科)学系の博士課程の過ごし方に関するtipsを提供しているサイト"
author: "yaaruga"
date: "2024-04-21"
categories: [Tips, Degree, Career]
---
博士課程を終えてみて強く痛感することのひとつは、社会科学系の博士課程の過ごし方、というのをもう少し強く意識しておくべきだった、ということだ。

ふつう博士課程には修士課程と違って強く標準化された年限がない（一応形式上は「3年」だがかなりの程度形骸化している）。特に社会科学系は伝統的に長期的に博士論文を執筆する文化がある。だからいつまでに修了しないといけないという目安が強くはない。自分も修士論文を終えての安堵、博士論文という目標の曖昧さも相まって、ダラダラと目的の定まらないインプットをしたり、作業環境の整備に没頭したりと、あまり有益ではない過ごし方をしてきた。もちろん最低限の成果は出せたと思うが、より計画的かつ戦略的に過ごしていれば、博士課程の院生は一種のフリーランスなのでそれに相応の戦略と計画が必要なのだと自覚していれば、はるかに高い生産性を発揮できていたと思う。ビジネスライクな言葉を使えば、要するに、プロマネ力、自走性が必要ということであるし、フリーランス労働者の一種であることを踏まえれば、ある意味で平凡なことだ。

自分より下の世代の人の相談に乗るときにもこういう話題になることがあるのだが、きちんとわかりやすくtipsをまとめるのはけっこう難しい。特に留学生などの人の場合、「博士号がないとテニュアはムリ」という業界レベルの「常識」も含めて、重要な背景知識をきちんと提供するのは――明らかに非常に重要であるにもかかわらず――とても難しい。私たちはふつう自分が日常的に行使している能力がいかにして養成されたのかなど反省しないので、当然のことではあるけれども。

ただ、ざっと調べたり聞いた範囲では以下のサイトが的確な情報を提供していて、とても有益に思われる。まったく網羅的でも厳密なものでもないし他にも有益なサイトはあるはずだが、いずれも私などよりはるかに研究者として優秀な方のアドバイスであり、おそらく社会学分野の人にはどれも役に立つ内容だと思う。分野ごとの違いはもちろんあるにせよ、こうした知見にざっと目を通しておけば「相場感」はつかめるのではないだろうか。

- [「研究職志望者のためのロードマップ（高松ゼミ編）」](https://sites.google.com/site/rietakamatsu/%E7%A0%94%E7%A9%B6%E8%81%B7%E5%BF%97%E6%9C%9B%E8%80%85%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AE%E3%83%AD%E3%83%BC%E3%83%89%E3%83%9E%E3%83%83%E3%83%97)

高松里江先生（立命館大学・社会学）のもの。学部時代から博士課程までのロードマップを簡潔かつ的確に説明している。

- [大学院での研究の組み立て方](https://www.tarotsurumi.com/kenkyu)

鶴見太郎先生（東京大学・社会学）のもの。研究者として社会化していくにあたっての基本的態度などが詳しく書かれている。

- [大学院で政治学を学びたい方へ](https://www.soc.hit-u.ac.jp/~takujit/graduate_school.html)

田中拓道先生（一橋大学・政治学）のもの。「大学院進学のリスクについて」のセクションは特にライフプランを設計するにあたってとても重要なことが書かれていると思う。

- [博士課程を標準年限で修了する（社会学2021年入学コホートの事例）](https://note.com/geronsoc/n/n1c7f8a28732f?sub_rt=share_pb)

新田真悟先生（学習院大学・社会学）が博士課程を3年で修了した経緯を回顧されているもの。他のはいずれも大学教員が指導の経験を踏まえて書いたものだが、これはより若い世代が一人称視点で書いたもの。


上に書いた以上に具体的かつ特定的な水準でいえば、すぐ思いつくこととして、

- 文献管理ソフト（Zotero、Paperpileなど）を使って系統的に文献を管理する
- Notionなどのアプリを使ってスケジュールやプロジェクトやタスクを系統的に管理する
- ZoomやGoogle Groupを使って研究会や勉強会を運営したり参加したりする
- 少なくとも年1回の査読論文の掲載と大規模な学会での発表をそれぞれめざす

などもあるだろう。今後、気が向くか必要になることがあれば、このあたりは自分なりに整理していみたいと思っている。