---
title: "【文献】Morehouse et al.(2023)「人類の社会集団はすべて人間的であるが、より人間的な集団もある」"
author: "yaaruga"
date: "2024-04-24"
categories: [Input, Teaching, Ethnicity/Race]
---
**Morehouse, Kirsten N., Keith Maddox, and Mahzarin R. Banaji. 2023. “All Human Social Groups Are Human, but Some Are More Human than Others: A Comprehensive Investigation of the Implicit Association of ‘Human’ to US Racial/Ethnic Groups.” *Proceedings of the National Academy of Sciences* 120(22):e2300995120.**

## 内容
ハーバード大学とタフツ大学の研究チームが13の実験に参加した6万人以上の被験者を対象に実施した潜在連合テスト（IAT）の結果を人種などの変数の観点から分析した論文。特に人種に関する認知がどのように「人間」や「動物」という属性の連想に関連するかを分析している。

明示的な質問に対する応答では、90％以上の被験者が白人も非白人も等しく人間であると明言している。これだけでは特に目新しくないのだが、注目すべきは、IATの結果である。国にかかわらず、白人被験者は、一貫して「人間」という属性を他の人種集団よりも白人と結びつけていた。すべての実験を通じて、白人参加者の61％が白人をより「人間」に、黒人をより「動物」に関連づけた。また、白人とヒスパニック系のテストを受けた白人についても同じ結果が出た。

これらの効果は、参加者の年齢、宗教、学歴を問わず当てはまるが、政治的信条や性別によって異なる。保守派と男性においては、「人間＝白人」という暗黙の結びつきがやや強かった。

他方、黒人、アジア系、ヒスパニック系の参加者はそのようなバイアスは見られず、自分たちのグループも白人も同じように「人間」と関連づけた。

同時に、探索的分析からは、東アジア諸国に居住する東アジア系の間では人間＝アジア系効果が一般的に観察された。つまり、「人間＝自己集団効果 Human=Own Group effect」そのものは西洋・白人に特殊なのではなく、ある特定の人種を人間カテゴリーに強く結びつける傾向は地域によるさまざまな人種集団の支配的位置を反映しているかもしれない。

## 感想
IATという手法は初めて知った。「次々と画面に呈示される刺激語のグループ分け課題を行い，概念どうしの組み合わせの違いから生まれる反応時間の差を指標として，概念間の連合の強さを測定する」^[藤井勉,2013,「対人不安IATの作成および妥当性・信頼性の検討」『パーソナリティ研究』22(1), 23-24.]手法で、特に意識的なアクセスが困難な思考や感情を測定するのに活用されているらしい。

この研究が何より面白いのは、さまざまな集団の成員が内集団をより「人間」と結びつける傾向そのものは先行研究ですでに報告されている一方、その傾向が当該社会における人種的序列を反映している可能性があるということだ。ありていにいえば、人種的マジョリティとしての地位が内集団＝人間という知覚上のバイアスをもたらす、ということだろう。

これがアメリカの白人だけに当てはまるというだけなら（それだけでも非常に重要であるにしろ）そこまで興味深くはないが、それがアメリカ以外の白人、さらに日本や中国の日本人や中国人にまであてはまる、というのは極めて興味深い。

もちろん内集団バイアス、またそれと特定の人種的序列との関係を示す研究はたくさんあるにせよ、植民地主義の歴史やグローバルな人種的境界まで視野に入れた実証的研究となるとそうはないだろう。

エスニシティ、差別、植民地主義などを授業などで振り返るときにぜひ参照してみようと思う。