project:
  type: website
  output-dir: docs
  
website:
  title: "Yu-Anis Aruga"
  google-analytics: "G-23K2TX0WXL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Works
      - href: project.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
      - href: posts.qmd
        text: Blog
    tools:
      - icon: twitter-x
        href: https://twitter.com/yu78730833
      - icon: facebook
        href: https://www.facebook.com/yuanis.aruga/
      - icon: instagram
        href: https://www.instagram.com/arugaaayyy/

  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Yu-Anis Aruga"

format:
  html: 
    theme: flatly # bootstrap 5 default
    page-layout: full
    fontsize: 1.2em
    linestretch: 1.7
    toc: true

editor: source

