project:
  type: website
  output-dir: docs
  
website:
  title: "Yu-Anis Aruga"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter-x
        href: https://twitter.com/
      - icon: facebook
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Yu-Anis Aruga"

format:
  html:
    theme: cerulean
    toc: true

editor: source

