project:
  type: website
  output-dir: docs

website:
  title: "Yu-Anis Aruga"
  site-url: "https://yaaruga.github.io/hp/"
  description: "Yu-Anis Aruga's Website"
  image: img/Miss_Van_y_Ciou.jpg
  open-graph: true
  google-analytics: "G-23K2TX0WXL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Works
      - href: project.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
      - href: teaching.qmd
        text: Teaching
      - href: blog.qmd
        text: Blog
    tools:
      - icon: twitter-x
        href: https://twitter.com/yu78730833
      - icon: facebook
        href: https://www.facebook.com/yuanis.aruga/
      - icon: instagram
        href: https://www.instagram.com/arugaaayyy/

  page-footer:
    right: "Built with [Quarto](https://quarto.org/), [RStudio](https://posit.co/), and [website-template](https://github.com/jtr13/quartobooktest)"

format:
  html: 
    theme: flatly 
    grid: 
      body-width: 900px
    page-layout: full
    fontsize: 1.2em
    linestretch: 1.6
    toc: true
    bibliography: BibTex/Website.bib
    link-citations: true
    citeproc: true
    csl: csl/american-sociological-association.csl
    css: css/style.css

editor: source