project:
  type: website
  output-dir: docs
  
website:
  title: "Yu-Anis Aruga"
  site-url: "https://yaaruga.github.io/hp/"
  description: "Yu-Anis Aruga's Website"
  image: img/Miss_Van_y_Ciou.jpg
  open-graph: true
  google-analytics: "G-23K2TX0WXL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Works
      - href: project.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
      - href: blog.qmd
        text: Blog
    tools:
      - icon: twitter-x
        href: https://twitter.com/yu78730833
      - icon: facebook
        href: https://www.facebook.com/yuanis.aruga/
      - icon: instagram
        href: https://www.instagram.com/arugaaayyy/

  page-footer:
    right: "Built with [Quarto](https://quarto.org/) and [RStudio](https://posit.co/)"
    left: "&copy; Copyright 2024, Yu-Anis Aruga"

bibliography: BibTex/Website.bib

format:
  html: 
    theme: flatly 
    page-layout: full
    fontsize: 1.2em
    linestretch: 1.7
    toc: true

editor: source

