project:
  type: website
  output-dir: docs
  
website:
  title: "Yu-Anis Aruga"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Home
      - work.qmd
      - projects.qmd
      - Contact.qmd
      - resource.qmd
    tools:
      - icon: twitter-x
        href: https://twitter.com/yu78730833
      - icon: facebook
        href: https://www.facebook.com/yuanis.aruga/
      - icon: instagram
        href: https://www.instagram.com/arugaaayyy/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; C
    opyright 2024, Yu-Anis Aruga"

format:
  html:
    theme: cosmo
    toc: true

editor: source

