---
title: "差別論の学習と指導のための参考資料"
about:
  id: me
  template: marquee
date-modified: last-modified
date-format: "YYYY-MM-DD"
toc-title: 目次
---

## はじめに

### 目的

- 有賀は所縁あって2024年度から複数の大学で「差別論」という学部生向けの大規模講義の授業を担当してきた。

- 元々有賀自身は社会学とエスニシティ論を名乗ることはあっても差別論と名乗ることはないし、差別という論題について社会科学の視点から体系的かつ初学者に通用する程度の平易さでもって扱った教科書はあまりないので、授業の教材づくりにはかなり苦戦してきた。

- ただ、色々な資料を漁り、試行錯誤しながらテキストや図を練りだし、学生の反応を見聞きするうちに、授業運営のコツ、つまり

  - どんな文献にもとづいて、トピック（サブトピック）を扱えばよいのか

  - どんな実例や資料を提供すればよいのか

  といったことの感触がおぼろげながらつかめてきたと感じてきた。

- このエントリは、以上を踏まえて、差別論を学部生に学んでもらうにあたっての主なトピックや資料についてまとめることを目的としている。

- 基本的にはトピック別に参考になる文献や実例を紹介するのに終始するが、付随的には

  - 学生がよく抱く疑問とそれに対する（有賀が考える限りでの）ありうべき答え方

  - 規範的・道徳的な論点をどう扱えばいいのか

  - 社会科学的なものの見方を学生が長期的に身につけるのに貢献できる（もしくはそうした見方を活かして受講できる）ためにはどうすればよいのか

    なども――諸方面に抵触のないかぎりかつ筆者の力量の及ぶ範囲で――言及したいと考えている。

### 免責事項と凡例

- この資料はあくまで有賀が自分自身の授業運営の参考のために作成したものです。
- 当然ながら有賀の独断や先入見を大いに反映しています。網羅性も適切性もまったく保障されません。
- そのため学生やその他の教員がそのまま読んで理解し参考にすることも念頭においていません。
- またこの資料に基づく効果的な指導や学習を保障するものでもありません。
- このページの更新は完全に不定期であり、永遠のβ版です。
- 以下にあげる資料のうち、学生が読むに適していると思うものは傍線、教員が読むに適していると思うものは太線で表しています。

## 差別論の理論的・歴史的前提

### 差別とはなにか

哲学・倫理学の領域ではそもそも差別の捉え方そのものをめぐってかなり豊富かつ高水準な議論が議論がなされている。論点は多岐にわたるが、さしあたりは

- 堀田義太郎，2021，「差別とは何か」清原悠編『レイシズムを考える』共和国，102–24．
- 池田喬・堀田義太郎，2023，「哲学から差別を考える」『月報司法書士』(613):10–21．
- 池田喬・堀田義太郎，2021，『差別の哲学入門』アルパカ．
- Thomsen, Frej Klem, 2017, “Discrimination,” *Oxford Bibliographies*, (<http://oxfordre.com/politics/view/10.1093/acrefore/9780190228637.001.0001/acrefore-9780190228637-e-202>).

などを読んでおくとよいだろう。

もう少し社会科学寄りなら

- Dovidio, John F and Elif G. Ikizer, 2019, “Discrimination,” *Oxford Bibliographies*, (<https://www.oxfordbibliographies.com/display/document/obo-9780199828340/obo-9780199828340-0233.xml>).
- 五十嵐彰，2025，「第１章第１節 差別とは何か」『可視化される差別：統計分析が解明する移民・エスニックマイノリティに対する差別と排外主義』新泉社．
- Pettigrew, Thomas F., 2015, “Prejudice and Discrimination,” James D. Wright ed., *International Encyclopedia of the Social & Behavioral Sciences*, 2nd ed, Amsterdam: Elsevier Inc., 828–33.

なども極めて参考になる。

また「差別」という概念は「平等」という概念とも密接に関連するため、後者についても大雑把な議論の構図を俯瞰しておくことが有益になる。

- Sturm, Susan, 2015, “Equality and Inequality: Legal Aspects,” James D Wright ed., *International Encyclopedia of the Social & Behavioral Sciences*, 2nd ed., Elsevier, 894–902.
- Malamud, Deborah C., 2015, “Discrimination and the Law,” James D. Wright ed., *International Encyclopedia of the Social & Behavioral Sciences*, 2nd ed., Amsterdam: Elsevier Inc.
- 齋藤純一，2017，『不平等を考える：政治理論入門』筑摩書房．
- 田中将人，2025，『平等とは何か：運、格差、能力主義を問いなおす』中央公論新社．

### 差別の歴史的形成

かつて20世紀アメリカを代表する社会学者の一人であるC. Tillyは社会学者が近代史へアプローチするにあたって重要な

- Massey, Douglas S., 2015, “Inequality, Social,” James D. Wright ed., *International Encyclopedia of the Social & Behavioral Sciences*, 2nd ed., Amsterdam: Elsevier, 908–13.

## 差別への理論的・実践的取り組み

- Nagel, Thomas, 1973, “Equal Treatment and Compensatory Discrimination,” *Philosophy and Public Affairs*, 2(4): 348–63.

### 人権の観念と反差別規範の萌芽

- 浜林正夫，1999，『人権の思想史』吉川弘文館．
- 筒井清輝，2022，『人権と国家：理念の力と国際政治の現実』岩波書店．
- スターンズ，ピーター・N，2022，『人権の世界史』上杉忍訳，ミネルヴァ書房．
- De Baets, Antoon, 2015, “Human Rights, History Of,” James D Wright ed., *International Encyclopedia of the Social & Behavioral Sciences*, 2nd ed., Elsevier, 367–74.

## 差別への理論的・実践的

### 第1世代の差別論

なお、「第1世代/第2世代」という区分は労働法学者のSturm, Sによるものに依拠している。[^1]

[^1]: Sturm, Susan, 2001, “Second Generation Employment Discrimination: A Structural Approach,” *Columbia Law Review,* 101(3): 458–568

### 第2世代の差別論

### 反差別法制の発展

### 積極的是正措置

「人種や性別による差別が長年にわたって行われていた場合、それを是正するために差別を受けていた集団について優先的な処遇を与える措置がとられることがある」[^2]。こうした措置を言い表す言葉として「アファーマティブ・アクション（AA）」「ポジティブ・アクション」「積極的是正措置」などがある。日本語では積極的是正措置と言われることも多い。これらの指示範囲は時代や話者や文脈によってもさまざまだが、学生向けに説明するなら、「積極的是正措置」か「AA」と略称するのが通りが良いだろう。

[^2]: 長谷部恭男，2022，『第8版 憲法』新世社，174．

私見では、AAは、マイクロアグレッション（後述）とならんで、学生の反応が良くも悪くももっとも白熱しやすいトピックのひとつだ。おそらく多くの大学という組織が卑近であり、性別という属性が卑近であり、なおかつ近年において「女子枠」がしばしばニュースの見出しを飾っているからというのがその理由だろう。

- Warikoo, Natasha, 2025, “The Demise of Affirmative Action in College Admissions,” *Annual Review of Sociology*, 51: 463–83.
- Warikoo, Natasha and Utaukwa Allen, 2020, “A Solution to Multiple Problems: The Origins of Affirmative Action in Higher Education around the World,” *Studies in Higher Education*, 45(12): 2398–2412, (Retrieved August 15, 2025, <https://doi.org/10.1080/03075079.2019.1612352>).
- Nagel, Thomas, 1973, “Equal Treatment and Compensatory Discrimination,” *Philosophy and Public Affairs*, 2(4): 348–63.

なお、積極的是正措置の効果、つまりそれが実際にどのように対象者の教育達成や労働市場上の成果につながっているのかも、同措置の規範的・経験的評価には重要である。

- Gisselquist, Rachel M., Min Jung Kim, Simone Schotte, and Chinmayi Srikanth, 2024, “Affirmative Action around the World: Insights from a New Dataset (Update),” WIDER Working Paper 2024, WIDER Working Paper, (Retrieved November 6, 2025, <https://www.wider.unu.edu/bibcite/reference/241688>).
- Leonard, Jonathan S, 2015, “Affirmative Action: Empirical Work on Its Effectiveness,” *International Encyclopedia of the Social & Behavioral Sciences*, 2nd ed., Elsevier, 256–61.

### 多文化主義・多様性・DEI

### 差別の観察と測定

- Eyer, Katie R, 2012, “That’s Not Discrimination: American Beliefs and the Limits of Anti-Discrimination Law,” *Minnesota Law Review*, 96(4): 1275–1362.

### 差別が起きる場面

### 差別を促す要因

### 差別がもたらす帰結

### 差別の巧妙化

### 差別の過激化

### 日本の文脈

- 苅谷剛彦，1995，『大衆教育社会のゆくえ：学歴主義と平等神話の戦後史』中央公論社．

## カテゴリ・グループ別の検討

### エスニシティ

### ジェンダー・セクシュアリティ

- 三成美保・姫岡とし子・小浜正子編，2014，『ジェンダーから見た世界史：歴史を読み替える』大月書店．
- 中村敏子，2021，『女性差別はどう作られてきたか』集英社．
- 久留島典子・長野ひろ子・長志珠絵編，2015，『ジェンダーから見た日本史：歴史を読み替える』大月書店．
- 姫岡とし子，2008，『ヨーロッパの家族史』山川出版社．
- 小山静子，1999，『家庭の生成と女性の国民化』勁草書房．
- 斎藤修，2013，「男性稼ぎ主型モデルの歴史的起源」『日本労働研究雑誌』55(9): 4–16．
- 牧原憲夫，2008，『日本の歴史 全集13 文明国をめざして』小学館．
- 牧野百恵，2023，『ジェンダー格差：実証経済学は何を語るか』中央公論新社．
- 筒井淳也，2016，『結婚と家族のこれから：共働き社会の限界』光文社．
- 若桑みどり, 2000, 象徴としての女性像：ジェンダー史から見た家父長制社会における女性表象, 筑摩書房.
- 落合恵美子，2019，『第4版 21世紀家族へ』有斐閣．
- 落合恵美子，2022，『増補新版 近代家族とフェミニズム』勁草書房．
- 藤田結子，2022，「メディアにおけるジェンダー表象」井川充雄・木村忠正編『入門メディア社会学』ミネルヴァ書房，178–93．
- 辻村みよ子，2008，『ジェンダーと人権：歴史と理論から学ぶ』日本評論社．
- 長谷川まゆ帆，2007，『女と男と子どもの近代』山川出版社．

### 障害・能力
