---
title: "戦後日本における「混血児問題」に関する調査"
toc: true
toc-title: メニュー
---

## プロジェクトの趣旨

周知のとおり、戦後の日本はアメリカ軍による占領からスタートしました。占領に伴い連合国軍の軍人や軍属が日本に進駐するなかで、彼らと一部の日本人女性の間に多くの子どもたちが生まれました。占領が始まった1945年から終了した1952年の間だけでも、その数は数万人に上るとされています。

こうした子どもたちは当時「混血児」と呼ばれ、さまざまな社会生活上の不利を経験してきたことが知られています。最近はこうした人々に焦点を当てたドキュメンタリー番組や書籍も登場し、彼らがそのバックグラウンドに関連してどのような経験をしてきたのかにも注目が集まっています。


::: {layout-ncol="2" style="font-size: 70%; line-height:1.0"}
{{< video https://youtu.be/KYngbLetPT0?si=PHQ16rwqdeUbAzPQ title='【差別と偏見のはざまで】戦争が生んだ子どもたち　' >}}

{{< video https://youtu.be/UUQ5bZtk6s4?si=PnKcoTI6Z0sUTejq title='映画「Yokosuka1953」予告編 ' >}}
:::


しかし、こうした人びとが実際にその人生や日常生活のなかで自らの人種的な背景に関係してどのような経験をしてきたのか、また彼らの経験に周囲の組織（政府、学校、児童福祉施設など）や家族がどう関与してきたのかということは、いまだに十分に明らかにされているとは言い難い現状が続いています。

このプロジェクトではこうした現状を踏まえて、さまざまなアーカイブやデータベースによる文書・映像資料の収集、さまざまなバックグランドをもつ「混血児」と呼ばれた人びとへのインタビューを行っております。

このプロジェクトの成果は以下の成果物にまとめられています。

## プロジェクトの成果

-   有賀ゆうアニース，2022，「人種差別の理解可能性と「混血（児）」カテゴリー――「混血少年連続殺人事件」を事例に」『年報社会学論集』35: 80-91．
-   有賀ゆうアニース，2022，「戦後「混血児問題」における<反人種差別規範>の形成――「混血児」概念の用法と文脈に着目して」『社会学評論』72(5): 154-171．
-   有賀ゆうアニース，2023，「戦後日本における「混血児」の国際養子縁組事業の成立と展開」『移民研究年報』29: 73-86．
-   有賀ゆうアニース，2024，「「混血児」としての経験と累積する差別：連合国軍軍人・軍属を父に持つ人びとの生活史から」『年報社会学論集』(37): 116–26．
-   有賀ゆうアニース，2024，「かれらが暮らすべき国はどこか：戦後日本における日米混血児の国際養子縁組事業をめぐって」豊田真穂編『優生保護法のグローバル史』人文書院，263–85．
-   有賀ゆうアニース，2026，『「混血児問題」の歴史社会学：戦後日本の人種的境界』新曜社．

