---
title: "研究プロジェクト Projects"
toc: true
toc-location: body
toc-title: "現在進行中のプロジェクト"
title-block-banner: false
about:
  id: me
  template: marquee
date-modified: last-modified
date-format: iso
---

現在、以下の２つの研究プロジェクトを遂行しています。

## PRJ1 外国にルーツを持つ若者の生活と意識に関する研究

在日外国人の定住化や国際結婚の増加に伴い、いわゆる「ハーフ」「ミックス」の人々、すなわち日本と外国の両方にルーツをもつ人々の日本社会における存在感が大きくなりつつあります。知人や友人のなかに当事者がいる、メディアや広告のなかで見かける、といったことも珍しくないでしょう。

::: {layout-ncol="2" style="font-size: 70%; line-height:1.0"}
![[Okki, United States Navy, Lhcollins, Humor Multishow, 樂活高縣, Rudra Nayan Das (original works); Mess (derivative work), CC BY-SA 4.0, via Wikimedia Commons]{style="font-size: 70%; line-height:1.0"}](img/Hafu_Collage.jpg){fig-align="center" width="393"}

![[西倉めぐみ・高木ララ監督『ハーフ』（2013年，ユナイテッドピープル）]{style="font-size: 70%; line-height:1.0"}](img/hafu1.jpg){fig-align="center" width="281"}
:::

その一方で、ハーフ/ミックスの人びとがどんな日常生活を営んでいるのか、その日常的な対人関係や社会的活動のなかでどのように自らの人種的・民族的な背景を経験し、意識しているのかについてはまだまだ研究が追いついていません。\
こうした現実を理解することは、今後ますます民族的・文化的多様化が進展していく日本社会の未来を構想していくためにも必要な課題になっています。

こうした状況を踏まえ、**「外国にルーツを持つ若者の生活と意識に関する研究」**という研究プロジェクトを開始しました。家族関係、友人関係、趣味、余暇など、広い意味でのライフスタイルのなかで、外国にルーツをもつことが、あるいは特定の人種的・外見的特徴をもつがどんな意味を持っているのかについて調べてきました。\
これまでの数十人のハーフ、ミックスの人びとへの取材から、黒人系の外見をもつがゆえのメイクやヘアスタイルの悩み、白人系であるがゆえの周囲からの過剰な好奇心...などなど、外国ルーツにまつわるさまざまな経験や意識を取材してきました。\
本調査では、日本人と外国人とをご両親にもつ方々に調査へのご協力をお願いしております。日々の生活やこれまでの人生のなかでの人種・民族的背景に関連してどんなことを経験してきたか、またそれについてどのような意識や理解をもっているかについて、ご意見や体験をお聞かせいただければ幸いです。

## PRJ2 戦後日本における「混血児問題」に関する研究

周知のとおり、戦後の日本はアメリカ軍による占領からスタートしました。占領に伴い連合国軍の軍人や軍属が日本に進駐するなかで、彼らと一部の日本人女性の間に多くの子どもたちが生まれました。占領が始まった1945年から終了した1952年の間だけでも、その数は数万人に上るとされています。\
こうした子どもたちは当時「混血児」と呼ばれ、さまざまな社会生活上の不利を経験してきたことが知られています。最近はこうした人々に焦点を当てたドキュメンタリー番組や書籍も登場し、彼らがそのバックグラウンドに関連してどのような経験をしてきたのかにも注目が集まっています。

::: {layout-ncol="2" style="font-size: 80%; text-align: center; line-height: 1.2;"}
!["The Week's Best Photo", *Jet* Sep 16, 1954\
黒人兵士と日本人女性を親にもつ女児を養子にした日本人夫婦の写真](img/1954-09-16_Jet.png){fig-align="center" width="289"}

!["Japan's Rejected", *Ebony*, Sep 22, 1967\
日本に暮らす黒人系混血児を特集したアメリカの黒人系雑誌 *Ebony* の表紙](img/1967-09-01_Ebony.png){fig-align="center" width="289"}
:::

しかし、こうした人びとが実際にその人生や日常生活のなかで自らの人種的な背景に関係してどのような経験をしてきたのか、また彼らの経験に周囲の組織（政府、学校、児童福祉施設など）や家族がどう関与してきたのかということは、いまだに十分に明らかにされているとは言い難い現状が続いています。\
このプロジェクトではこうした現状を踏まえて、さまざまなアーカイブやデータベースによる文書・映像資料の収集、さまざまなバックグランドをもつ「混血児」と呼ばれた人びとへのインタビューを行っております。
