---
title: "外国にルーツをもつ若者の生活と意識に関する調査"
toc: true
toc-title: "外国にルーツをもつ若者の生活と意識に関する調査"
---

## プロジェクトの趣旨

在日外国人の定住化や国際結婚の増加にともない、外国出身の両親を持ついわゆる「第２世代」「２世」の人びとや、外国出身の親と日本出身の親を持ついわゆる「ハーフ」「ミックス」の人びとの存在感が増しています。学校の友人や近所の隣人や職場の同僚のなかに当事者がいる、メディアや広告のなかでスポーツ選手や芸能人を見かける、といったことも珍しくないでしょう。

::: {layout-ncol="2" style="font-size: 70%; line-height:1.0"}
![[Okki, United States Navy, Lhcollins, Humor Multishow, 樂活高縣, Rudra Nayan Das (original works); Mess (derivative work), CC BY-SA 4.0, via Wikimedia Commons]{style="font-size: 70%; line-height:1.0"}](img/Hafu_Collage.jpg){fig-align="center" width="393"}

![[西倉めぐみ・高木ララ監督『ハーフ』（2013年，ユナイテッドピープル）]{style="font-size: 70%; line-height:1.0"}](img/hafu1.jpg){fig-align="center" width="281"}
:::

その一方で、第２世代やハーフ/ミックスの人びとがどんな日常生活を営んでいるのか、その日常的な対人関係や社会的活動のなかでどのように自らの人種的・民族的な背景を経験し、意識しているのかについてはまだまだ研究が追いついていません。こうした現実を理解することは、今後ますます民族的・文化的多様化が進展していく日本社会の未来を構想していくためにも必要な課題になっています。

こうした状況を踏まえ、**「外国にルーツをもつ若者の生活と意識に関する調査」**プロジェクトを開始しました。家族関係、友人関係、趣味、余暇など、広い意味でのライフスタイルのなかで、外国にルーツをもつことが、あるいは特定の人種的・外見的特徴をもつがどんな意味を持っているのかについて調べてきました。

このプロジェクトでは、日本人と外国人とをご両親にもつ方々、またご両親とも外国人である方々に調査へのご協力をお願いしております。日々の生活やこれまでの人生のなかでの外国ルーツに関連してどんなことを経験してきたか、またそれについてどのような意識や理解をもっているかについて、お話を聞かせていただいております。

以下、このプロジェクトによるこれまでの成果と協力者の募集を記載します。

## これまでの成果

-   有賀ゆうアニース，2022，「「ハーフ」の身体とファッション・メイク――「#和顔ハーフ」から考える」『ZOZO NEXT FASHION TECH NEWS』 [Link](https://fashiontechnews.zozo.com/series/series_fashion_technology/ariga_yu_anis)
-   佐藤祐菜・有賀ゆうアニース，2022，「「ハーフ」の文化社会学に向けて——複数の人種的背景を持つ若者の文化実践についての探索的調査」日本社会学会大会第95回大会．
-   Sato, Yuna. and Yu-Anis Aruga, 2023, Cultural participation and Identities of Multiethnic and Multiracial Youth in Japan,” XX ISA World Congress of Sociology. (Online)

## ご協力者の募集

このプロジェクトでは、外国にルーツをもつ若者で、インタビューに参加していただける方を募集しています。「外国にルーツをもつ若者」とは、以下の条件に合致する人びとを指しています。

-   両親、もしくはその一方が外国生まれであること。
-   日本でずっと暮らしていること。あるいは一定期間は日本で暮らした経験があること。
-   1980年以後に生まれていること。

以下は、調査への参加にあたってのポイントです。

-   事前に基本的な情報に関するアンケート（10\~15分程度で回答いただけます）に回答いただいた後に、[１〜２時間程度のインタビュー]{.underline}をご依頼します。
-   [インタビューは対面、もしくはオンラインのどちらかで実施します]{.underline}。
-   ご協力で得られた[データはプライバシー保護のため匿名化され]{.underline}、研究目的以外で用いられることはありません。
-   研究成果は、学会発表、論文、書籍などの形で公表されます。研究成果がインターネット上に公表されることがありますが、その場合も[匿名化することでプライバシーを保護します]{.underline}。
-   ご協力いただいた後には、謝礼として、ギフトカードもしくは現金を贈呈いたします。
-   本調査は、独立行政法人日本学術振興会の研究助成（課題番号 24KJ0187）、ならびに大阪公立大学経済学研究科の研究倫理審査委員会による承認を受けています。

もしも興味をお持ちでしたら、[こちら](contact.qmd)に記載されているメールアドレス、もしくはこのホームページの右上にあるSNSのアイコンからアクセスできる有賀のアカウントへのダイレクトメッセージなどで、お気軽にご連絡ください。ご質問などもお気軽にどうぞ。
