---
title: "【文献】Bloemraad et al. 2023「移民統合を解きほぐす： 概念、メカニズム、文脈」"
date: "2024-06-18"
categories: [Imput, Teaching, Immigrant, Methodology]
---

**Bloemraad, Irene, Victoria M. Esses, Will Kymlicka, and Yang-Yang Zhou. 2023. “Unpacking Immigrant Integration: Concepts, Mechanisms, and Context.” Pp. 1–29 in *World Development Report 2023: Migrants, Refugees, and Societies*, edited by World Bank. Washington, D.C.: World Bank.**

世界銀行の年次報告書に掲載された移民統合政策の概論というだけあって、社会学、心理学、政治理論、政治科学のそれぞれを代表する超豪華な執筆陣。そして内容も凄まじく勉強になる大変良い論文。

# 内容

## Introduction 1-

-   先行研究によれば移民への偏見・敵意は経済的・文化的要因に規定されることが明らかにされている

-   移民・移民政策の社会文化的次元を議論する際に参照されている文化的距離の仮定

    1.  文化の違いは客観的な事実であり、特定の移民が受け入れ社会と文化的に近いか遠いかは、簡単に測定できる。
    2.  文化的距離は、統合を成功させるにあたっての「問題」である。
    3.  統合を成功させるためには、そもそも文化的距離のある移民を入国や滞在から排除するか、同化主義やその他の対人的な 「文化的収束」モデルによって、移民の文化的距離を縮める必要がある。

-   これらの仮定はミスリーディングなものであり、文化的距離という想定そのものを問い直す必要がある。

    > ある移民グループが文化的に近いと認識されるか、あるいは文化的に遠いと認識されるかは、客観的な差異から生まれるものではない。むしろ、そのような認識は、ある種の共通点や相違点が強調される一方で、他の類似点や相違点が無視されたり否定されたりする、複雑な境界形成過程から生じる。このような境界形成プロセスは、歴史的に偶発的であり、制度的に媒介され、政治的に構築されたものである。また、文化的差異がある限り、それが常に統合の「問題」であるとは限らず、統合の成功には文化的同化や文化的収束が必要なわけではない…。文化的維持、文化的適応、文化的収束の様々な形態や組み合わせを含む、幅広い統合のモデルが存在する。（3）

## Misdiagnosis: Cultural distance is not a self-evident problem 4-

::: callout-important
**文化的距離を客観的で固定的な現実とみなすことは反移民感情を分析するにあたって不正確かつ不十分である。**
:::

### Erroneous remedies when cultural distance is viewed as objective reality 4-

移民の文化的距離が客観的事実と想定されるとき、政策立案者や学者や市民は以下の解決策を提案してきた（4f）

1.  文化的同化
2.  対人的関与をつうじた文化的収束
3.  文化的分離
4.  物理的排除／放逐

### “Cultural distance” is historically variable and politically constructed 5-

**文化的距離は歴史的に可変的かつ政治的に構築されている。**

> 移民グループが移民先社会と似ていると見なす基準、あるいは異なると見なす基準は、原理的にさまざまであり、どの基準を選ぶかによって、同じグループでも非常に近いと見なすことも、非常に遠いと見なすこともできる。...受け入れ社会は、文化的距離を判断する基準を変えることができるし、実際に変えているのであり、それによってどのグループを近いと見るか、遠いと見るかも変えているのである。（5）

-    宗教、国籍、出身国、言語、人種などによって複合的に文化的距離は形成される。
-   20世紀前半までのアメリカをはじめとする入植者植民地国家はいずれもプロテスタントを主流として形成された
    -   しかし20世紀後半をつうじてかれらは主流社会の成員とされるようになった（Waters 1990）
    -   こうした変化は黒人の大移動や公民権獲得といった動向のなかで人種的距離がより重要視され、相対的に白人内部の結束が高まったことに起因していた（Fouka et al. 2022）

> したがって、文化的距離に関する主張は、額面通りに受け取るのではなく、慎重に吟味する必要がある。実際、何が「客観的に」遠いかは社会的に構築されたものであり、したがって、どの「文化的」目印が吟味の対象に選ばれるかは、場所や時間、グループによって変わりうるし、これらの目印の意味や価値も変わりうる。（6）

## Unpacking prevalent concepts and measures of immigrant integration 7-

::: callout-important
**同化による統合というアプローチにいかなる限界があるのか、それがより多次元的かつ文化的差異に受容的な統合のモデルにどのように移行しつつあるのか。**
:::

> 文化的距離が客観的な事実であり、客観的な問題であるという考え方は、分析的に間違っているだけでなく、「統合」とは何かという理解を歪めている。文化的距離が客観的な問題であると仮定するならば、統合を成功させるには移民の文化的距離をなくすこと、つまり同化が必要であるように思われる。実際、過去150年間、移民の統合を考える際には、主流への適合かメルティング・ポット（人種のるつぼ）的な同質性といった同化の考え方が支配的であった。（7）

### Older approaches to social inclusion: Assimilation 7-

-   同化理論の問題点
    -   伝統的に移民の文化的距離への対応としては出身国の文化の消去と受け入れ国の文化への適応を通じた一方的同化が強調されてきた
    -   その主要な想定は、受け入れ社会との差異は一般的に問題であり、同化には差異の消去が必要であるというものだった
-   この想定には実質的にも規範的にも重大な問題がある（7）
    -   同化の基準としてなにが準拠集団を構成するのかが自明ではない
    -   移民の受け入れ社会に対する文化的差異は移民自身のみならず受け入れ社会にとっても便益をもたらしうる
    -   自由民主主義の基本的価値観である文化的選択の自由を侵害しうる
-   近年の新同化理論はより微細な仕方で移民の同化を理解しようとしている（7f）
    -   文化的同化よりも社会経済的同化を移民にも受け入れ社会にも望ましいものとしてより重視する

    -   また移民の同化が受け入れ社会を多様化させ、文化的差異が相対的に問題ではならなくなる可能性も考慮している

    -   他方、この理論は依然として統合の成功を差異の縮小によって説明しているという限界がある

### Social inclusion and integration as process: Intergenerational change 8-

-   同化理論に代替する社会的包摂の理論は、移民の統合・包摂を世代横断的かつ長期的な過程として理解する（8f）

    -   この枠組のもとでは、終着点をどこに設定するのかという問題がある
    -   他方、受け入れ社会の政府はますます、即時の統合を期待するようになっている

    > プロセス・アプローチに欠けているのは、なぜ移民の文化的アイデンティティの維持が統合と両立するのか、なぜ移民の民族的アイデンティティやコミュニティへの愛着が、移民先社会への愛着と両立しうるのかという説明である。（9）

### Bidimensional models of acculturation: The individual and group level 9-

> 「文化的距離」は客観的で固定的な問題ではないし、同化は統合の成功のために必要であるわけでもない。むしろ、移民の統合が成功するのは、彼らが自らの出自と受け入れ社会の両方へと帰属意識を有するとき、そして特に受け入れ社会の側がこの多元的帰属を許容するシグナルを発しているときである。（12）

### Destination societies: Civic integration and multicultural policies 10-

-   受け入れ社会が移民への文化変容の期待を表示するのは移民の定住・居住・帰化・文化的受容に関する政策をつうじてである（10f）
    -   総じて戦後の西欧諸国では国籍政策や出入国管理政策の水準において多文化の受容と自由化を促進してきた（Banting and Kymlicka 2013）
    -   他方、近年は受け入れ社会の文化的知識や政治的理念の共有を強調する市民的統合政策が発展している（Goodman 2014, 2022）
-   多文化主義政策と市民的統合政策はどのような帰結をもたらすのか（11）
    -   多文化主義政策は多様な文化を受容・承認することで社会的包摂に貢献しうる
    -   市民的統合政策は移民が受け入れ社会に社会文化的に統合されるのを促進しうる一方、伝統的な一方向的な同化をもたらしうる（Bloemraad and Wright 2014）
    -   総じて、多文化主義政策が充実している国の移民ほどエスニックアイデンティティも受け入れ国への帰属意識も強く（Berry 2005; Bloemraad and Wright 2014; Nguyen and Benet-Martinez 2013）、帰化に積極的である（Wright and Bloemraad 2012）
    -   他方、同化主義的政策の効果についての知見は必ずしも一貫しておらず、同化主義が本当に移民の同化を促進するとは断言できない
        -   20世紀初頭に免許や職業に関する市民権制限が強かった米国の州に住んでいた移民は、逆に、非市民に機会を与える制限が緩やかな州よりも帰化する確率が低かった（Bloemraad 2006b）
        -   フランスにおける2004年のスカーフ禁止令法は宗教的アイデンティティを強化し、ムスリムの少女の教育達成度を低下させ、労働市場の軌道に長期的な影響を及ぼした（Abdelgadir and Fouka 2020）。

## Rethinking difference and inclusion 12-

::: callout-important
**固定的で客観的な文化的距離という仮定を離れるために(1) 境界策定 boundary work、および (2) 勾配的成員性** gradient membership **の視点を導入する。これらは、社会文化的次元における反移民感情の普及と移民の包摂の障害をよりよく理解するための代替的な概念的枠組を提供する。**
:::

### Outsiders, insiders, and boundary-making projects 12-

-   移民の内集団／外集団としての分類はさまざまな境界によって多面的に規定される（12f）
    -   言語や宗教（Zolberg and Woon 1999）

    -   国籍や人種（Alba 2005）

    -   文化と民族性（Kasinitz et al. 2008）

    -   労働・稼得能力（Bloemraad 2013; Park 2005; Warikoo and Bloemraad 2018）

    -   政治イデオロギー（Holland et al. 2023）

### Gradient membership 13-

**境界策定の視点をとることで、成員性を多元的で連続的で相対的な状態として理解することができる。**

-   人々の成員資格は内部と外部の二分法に還元されるものではなく、むしろ他の集団や特定の理念型との比較において構成される（Bloemraad 2018, 2022）

    -   移民の社会的包摂は、人種や血統や宗教といった属性的特性だけでなく、政治観や社会観のような価値・態度上の指標、言語や雇用のような行動上の指標などさまざまな境界によって複合的に規定される
    -   「研究者は、いつ、誰に対して、どのような文脈において、可能的な差異の指標が積み重なってお互いに補強し合うのかを検討することができる」（13）

-   成員資格の指標がどのていど可変的・恒常的なのかは複数の文脈的要因に規定される

    > 「形式化、複雑さ、合意におうじて、特定の成員性の指標はほかのものよりも可変的で変化や再解釈に開かれており、それが包摂の余地を提供するのである。（13）

    -   国籍法などによってどのていど形式化されているのか
    -   言語能力の基準のように、その基準の適用がどの程度複雑なのか
    -   概念の意味をめぐる合意がどの程度形成されているのか（なにか「アメリカ」文化なのか）

-   人々が成員性を勾配的・連続的な状態として帰属していることを把握するためには境界策定のアプローチが有用である（13f）

    -   マジョリティ言語を話し雇用されている非正規移民のように、一面では外集団でありながら別の面では内集団であることもある（Bloemraad 2022; Patler 2018）

    -   さらに、社会的包摂の評価は受け入れ社会と移民との関係だけでなく、複数の移民集団間の相違、受け入れ社会の複数のコミュニティの間の相違、そして世界中の異なる受け入れ社会の間の相違を考慮しなければならない（Kim 1999; Maxwell 2012; Shams 2020; Winter 2011）

## Strategies and remedies: The way forward 14-

::: callout-important
文化的同化だけでは必ずしも文化的距離の縮小には十分ではなく、文化的距離自体が受け入れ社会の態度に依存するとすれば、どのようにその態度を改善すればよいのか？それには、個人の信念や態度を変容させるための個人レベルの介入、境界編成に関連する政策・制度を変容させるための集合的・制度レベルの介入が必要である。
:::

### Individual-level interventions 14-

-   移民に対する個人レベルの偏見を低下させる方策として移民についてのネイティブの誤認を是正すること、移民への共感や視点取得を促すこと、集団間での接触をもたらすこと、などが検討されてきた。
-   移民に対するネイティブの態度と信念を肯定的に変容させるための個人レベルの介入方法がこれまで大規模な研究によって検討されてきた
    1.  受入社会の成員への教育・啓発により、移民の人口や態度や行動についての誤認を是正すること
        -   マジョリティとマイノリティが基本的な社会的市民的規範を共有しているという認識が偏見を低下させる（Choi et al. 2022）

        -   一定の条件のもとでは効果的だが（Abascal et al. 2021; Grigorieff et al. 2020）、場合によっては反動や既存の態度の強化にもつながる（Nyhan and Reifler 2010）
    2.  移民への共感や視点取得を促すこと
        -   移民の立場になるよう促すこと（Adida, Lo, and Platas 2018）

        -   移民自身の物語を視聴すること（Audette, Horowitz, and Michelitch 2020）

        -   10分程度の個人的な会話（Kalla and Broockman 2020）
    3.  集団間接触
        -   実験研究は軽微な接触であっても移民への肯定的態度を促進することを報告している（Andersson and Dehdari. 2021; De Coninck, Rodríguez-de-Dios, and d’Haenens 2021; Getmansky, Sınmazdemir, and Zeitzoff 2018; Ghosn, Braithwaite, and Chu 2019; Knappert et al. 2021）

        -   メタ分析によれば、実験室の外部における接触も長期的効果を及ぼす（Lemmer and Wagner 2015）

        -   他方、より多様な文脈を考慮した研究によれば、接触が生じる文脈が接触の効果の方向や程度を規定することも判明している（Ditlmann and Samii 2016; Lowe 2021; Mousa 2020; Scacco and Warren 2018; Zhou and Lyall）

### Institutional and collective remedies 15-

-   移民に対するネイティブの文化的距離の縮小のためには、制度的・構造的水準における解決策も追求する必要がある

    > 境界策定の政治は統合論議の中心にあるべきである。（14）

-   移民に対するネイティブの文化的距離の伸縮は、エリートによる投票キャンペーン、政府による民族的人種的カテゴリーの策定、意思決定者による制度・政策の設定といった制度的・構造的要因に強く規定される（15f）

    -   構造化・制度化された環境のもとでのマイノリティとの接触はマイノリティに対するネイティブの好意的態度を醸成する（16）

    -   人種的に統合された近隣で生育した白人は生涯を通じてより進歩的態度をとりやすい（Brown et al. 2021）

    -   軍隊や学校でマイノリティの同僚がいるとマジョリティの態度が好転するだけでなくマイノリティの成績も改善する（Corno, La Ferrara, and Burns 2022; Finseraas and Kotsadam 2017）

    -   アラブ人の医者に治療されることでアラブ人一般へのユダヤ人の偏見が低下する（Weiss 2021）

    -   ウガンダにおける難民の定住・統合政策は移民へのネイティブの態度を好転させた（International Rescue Committee 2016; Zhou, Grossman, and Ge 2023）

    -   社会制度、公共政策、そしてエリートのリーダーシップは移民の社会的包摂に重要である

### Rethinking national narratives 16-

-   文化的距離は自動的に国民としての同胞意識を阻害するわけではなく、むしろ複合的な文化的要因によって偶発的かつ選択的に境界が画定される

    > 人々は集団間の境界を引くときにどの文化的因子に焦点を当てるかを絶えず改訂し作り替えている。人種、宗教、言語、価値、衣服、食事におけるさまざまな差異はいずれも「文化的に遠い」者としてある集団をラベリングすることを正当化するために発動される。しかし、同時に、もし人々がその代わりに「われわれ」であるという意識ないしともに帰属していることを強調することを願うなら、こうした差異は無視されうるものでもある。したがって、ある社会の成員は、特定の客観的な、測定可能な意味において文化的に近い人々に対してのみ、またかれらにたいして自動的に共属意識を感じるのではない。むしろ、ネイティブたちは先行する「自分たちはだれなのか」という感覚をもっているのであり、その基盤の上で、「われわれ」というサークルの内部における特定の文化的差異を無視すると判断し、また他方でそのサークルの外部にいる者たちとの文化的差異を誇張するのである。（16）

-   このことが含意するのは、内集団意識がどのようにして形成されるのか、という問いである。

    -   近代世界においては国民国家を軸として内集団・外集団意識、ナショナル・アイデンティティが形成されている
    -   そのため移民に対する境界の引かれ方はその国の支配的な「ネーション」像によって強気規定される

-   ナショナル・アイデンティティそのものが一般に移民への敵意や偏見に結びつくという知見も得られている（Sides and Citrin 2007; Sniderman and Hagendorn 2007）（16f）

-   一方、この結びつきの程度や仕方はどの国なのか、どのようにネーションが喚起されるのかに依存している（17）

    -   ネーションの成員として移民が想定されており、多文化的な意識が強い国々では、ナショナル・アイデンティティは必ずしも反移民感情に結びつかない（Breton 2015; Johnston et al. 2010; Esses et al. 2006; Esses et al. 2021）
    -   場合によってはナショナル・アイデンティティが喚起されることが移民の包摂を肯定する意識につながることもある（Voss, Silva, and Bloemraad 2020）
    -   ナショナル・アイデンティティが市民的か文化的かにより、ナショナル・アイデンティティが移民への態度に与える影響は異なる（17）

-   近代社会の基本的な組織原理としてのネーションを踏まえると、移民の社会的統合においてナショナル・アイデンティティの考察は不可欠である。

### Enabling migrant political agency and voice 17-

::: callout-important
**移民の政治的統合はシティズンシップ・シティズンシップ政策によって強く規定される。移民の政治的主体性と要求の機会を担保することが受け入れの文脈を形成し社会的包摂を促す。**
:::

-   移民は歴史的に文化・経済的同化を受け入れ社会によって強く要求／推進されてきた一方、政治的統合は強く制限されてきた（17）

-   移民とネイティブの境界の構築・維持のメカニズムとして特に重要なのがシティズンシップ・国籍政策である（17f）

    -   その他にも、学校、メディア、近隣、職場、軍隊など、相互作用の文脈を提供する機関、「私たち」と「彼ら」に関する言説、および／または行動や意思決定のルールを確立する政策が含まれる

    -   出生地主義にもとづく移民2世への国籍付与はアメリカ大陸諸国（合衆国、カナダ、カリブ諸国、ラテンアメリカ諸国）では一般的である一方、アジア・アフリカ・中近東諸国ではほとんど制度化されていない。結果、アメリカ大陸諸国とそれ以外では移民の政治的統合に大きな差が生じている（17f）

-   国籍の取得の規制緩和は移民の社会的包摂において不可欠である。

    -   国籍を開放することで、より国民の人口構成が変化するだけでなく、移民は受け入れ国への帰属意識を強め、国民的アイデンティティが意味するものの概念を長期的に変化させる（18）
        -   ただし、フランスにおけるアフリカ系移民のように可視的であるがゆえに、国籍を取得しても周囲から国民として扱われにくい集団もいる

        -   たんに帰化するだけでなく（Fick 2016）、帰化した同胞とともに居住すること自体がその国への帰属意識を強める（Abascal 2017）

            > 要するに、国籍を通じた包摂は帰属を促進する。（18）
    -   実利的な観点からは、国籍の取得は、国家の領土へのアクセス、強制送還からの保護、公共セクターへの就労、高賃金の職業への就職を提供する。
    -   多くの国は高度な権利や便益を国民にのみ限定するという意味で国籍によって政治システムを閉鎖しているゆえに、国籍の取得は制度的・政治的包摂を促す
        -   移民住民が多く、国籍制度が開放的な国では移民的背景をもつ候補者が多く、結果的に反移民的な施策が講じられにくい。「シティズンシップは社会的制度的編入を前進させるための相対的に容易な政策手段である」（18）。

## Conclusion 19-

::: callout-important
移民統合はゼロサム的な過程ではなく、むしろ既存のアイデンティティやネットワークや文化を保持しつつ受け入れ社会の成員としての地位を獲得していく過程である
:::

> 移民が根をあげて他の社会に移り住むとき、彼らの生活は変わり、新しい環境に適応し、新しいルールや言語を学ぶ必要があることを知っている。中には、新しい国で新しい人生を切り開くこの機会を喜ぶ人さえいるかもしれない。しかし、変化と適応をゼロサムのプロセスと見なすべきではない。あたかも、移民がもともとの家族的、民族的、宗教的、文化的な結びつきや遺産を隠したり捨てたりしなければ、新しいルールや人間関係に習熟できないかのように考えるべきではない。個人レベルでは、移民は古い愛着やアイデンティティを捨てることなく、文化的レパートリーを拡大する多種多様な「順化戦略」を持っている。また、社会レベルでは、移民先社会は、移民が参加し、帰属するためのルートを提供し、こうした適応戦略を支援するための多様な政策オプションを有している。（19）

-   移民の経済的利益がネイティブの経済的不利益に連動するとは限らないように、移民の社会文化的統合は移民の出身国の文化・アイデンティティの維持と両立する。それを実現させるためには、「文化的距離」が固定的で永続的な統合の障壁であるという固定観念を排することが必要である。（19）

------------------------------------------------------------------------

# 感想

-   超豪華な面子が書いた最新論文とだけあって、広大な理論的射程と豊富な実質的知見とに裏づけられた、卓越した論文だった。素朴に「移民研究ってこんなにスリリングに書けるのか！」と感じた。
-   統合をゼロサム的過程とする考え方――移民としてのアイデンティティとネイティブとしてのアイデンティティが排他的であり、文化的均質化こそが統合に不可欠であるという仮定――を分析的にも規範的にも批判するのは、それ自体としては目新しいものではないけれど、移民統合においてあまりにも容易かつ悪質に持ち込まれる仮定を牽制・解除するという意味でとても有益。
    -   欧米諸国だけが取り上げられているが、日本に限ってもこうした多元的アイデンティティと統合の関係が量的研究から示唆されている（福岡・金 1997; 五十嵐 2021）
-   そしてこうした過程を逃れるために象徴的境界アプローチに着目しているのは今後の自分自身にとってとても重要である。このアプローチの意義は今後のアーリーキャリアのなかで経験的にも理論的にも追求していきたいと思っている。

# 感想で引用した文献

福岡安則・金明秀， 1997， 『在日韓国人青年の生活と意識』東京大学出版会．\
五十嵐彰， 2021， 「移民の日本に対する帰属意識：水準と規定要因」永吉希久子 編『日本の移民統合：全国調査から見る現況と障壁』明石書店，186–207．
