---
title: "【文献】外村大（2011）「ポスト植民地主義と在日朝鮮人」"
author: "yaaruga"
date: "2024-04-27"
categories: [Imput, Immigrant, Ethnicity/Race, Teaching, Korean]
---
**外村大，2011，「ポスト植民地主義と在日朝鮮人――帝国崩壊後の民族関係の変遷に着目して」日本移民学会編『移民研究と多文化共生』御茶の水書房，186-206.**

## 内容

在日朝鮮人史研究の大家である筆者が日本人との民族関係、ポスト植民地主義の観点から在日朝鮮人の現代史を概論した論考。在日朝鮮人史の復習の一環として再読。

筆者はまず、敗戦後に知識人や政治家や政党が提示した戦後の政治構想には朝鮮国家の独立・発展や日本国内に暮らす在日朝鮮人の生活・権利保障はほとんど視野に入っていなかったこと、在日朝鮮人もまた長らく祖国への強い志向や民族団体の影響力のもとで日本社会への統合という課題を共有してこなかったことを確認している。

そして、冷戦構造や平和・民主主義の理念という前提の上での日本国内における保革対立や高度成長、朝鮮半島の分断という状態に対応して形成された「在日朝鮮人の日本社会への帰属の回避・参加の抑制による日本人との摩擦の回避」という基調「民族関係の55年体制」と概念化している（193f）。この枠組みのもとでは、一方で、朝鮮人については祖国朝鮮との紐帯の維持と祖国への貢献という価値が強調され、朝鮮人の生活状況に関係する課題の軽視という傾向が生じた。他方で、日本人については在日朝鮮人は日本社会の成員ではないという理解が広まるとともに、植民地支配や民族的偏見・迫害への反省が弱まるという傾向、単一民族国家としての自己理解が生じた。「それは日本人の加害の歴史反省の確立や民族差別の克服、在日朝鮮人の歴史と存在を尊重したうえで彼らを社会の一員として位置付ける環境の形成といった“懸案事項”の解決を生みださなかった。むしろ、それの解決を先送りする作用を内包していた」（195）。

この「民族関係の55年体制」が揺らいでいくのは1980年代以後のことである。1970年代以来の民族団体主導ではない民族差別反対運動の広がり、民族団体の影響力の衰退、2世以後における祖国との距離の増大といった傾向のなかで、在日朝鮮人の定住・統合という実践的課題が浸透し、定住を前提とする社会参加が重視されるようになった。

こうした日本社会への定住・統合への傾向は現在でも進行中であり、「要するに、在日朝鮮人が日本社会への参加・帰属を抑制することで日本人との摩擦を回避するという民族関係の55年体制は溶解消滅しつつあり、日本社会への参加の深化・帰属の明確化の動きは今後も進むことが予想される」（200）。しかし、たしかにこの間に日本社会でも在日朝鮮人の社会的・政治的権利がかつてよりも拡充した一方で、民族的包摂への意識はいまだに日本人の間では重要な政治課題とは認識されず、日本社会の側がいかに自己変革するのかといった視点は依然として乏しい。政策や制度の変革だけでなく、在日朝鮮人の歴史や現況について日本人が学習すること、そして在日朝鮮人を安全保障上の危険として理解する見方を抑制し緊張関係を縮減していくことが求められている、という判断で論考は締めくくられる（203-4）。

## 感想

日本移民学会の論集なので概論的性格が強い論考だし、特別目新しい知見はないが、「民族関係の55年体制」という概念化は中々興味深い。1950年代中盤を日本現代史の歴史的転換点とする議論は多いが^[Dower, John. 1993. “Peace and Democracy in Two Systems: External Policy and Internal Conflict.” Pp. 3–33 in *Postwar Japan as History*, edited by A. Gordon. Berkeley: University of California Press.]、そうした動向も踏まえつつ民族意識・関係の歴史を整理すると、マクロなレベルでエスニシティ・ナショナリティの歴史的編成を考えるのに役立つだろう。脱植民地化と多文化主義の間には連続性があるというJoppkeの指摘を踏まえると、日本において脱植民地化の不徹底と多文化主義の不徹底の間に連続性を見出すこともできるだろう。

:::{.callout-note}
## 「多文化共生」の源流？
「……戦後初期を含めて、多文化共生という語が一般的になる以前から、在日朝鮮人が日本国家や日本人に対して求めていたことのなかには、今日言うところの多文化共生の課題と共通する要素が含まれている。」（外村 2011: 188）
:::    

:::{.callout-note}
## 民族関係の55年体制の崩壊と単一民族意識の存続
「……在日朝鮮人の日本社会への参加の拡大と帰属の重視の傾向は近年、明白となり、民族関係の55年体制は崩壊しつつある。だがそのことに対応した日本社会の側の変革の課題はなお意識されず、逆に在日朝鮮人に対する警戒も表面化している現状があると言えよう。」（外村 2011: 201）
:::    