---
title: "日本における外国人のメディア表象に関する内容分析的研究をまとめてみた"
author: "yaaruga"
date: "2024-05-01"
categories: [Output]
draft: true
---

今回有賀が寄稿した以下の書籍が出版されました。 **藤嶋陽子・宮﨑悠二・陳海茵編著，2024，『広告文化の社会学』北樹出版.**

有賀は以下の章を寄稿しています。 **有賀ゆうアニース，2024，「広告表現のなかの／とエスニシティ」藤嶋陽子・宮﨑悠二・陳海茵編著『広告文化の社会学』北樹出版.**

題名のとおり、広告表現におけるエスニシティ（民族と人種）について初学者が学習するために、基本的な概念や視点、主要な研究とその知見、また歴史的・現代的なトレンドやイシューなどを整理したものです。外国にルーツをもつ人たちがどのようにメディアと関係しているのか、人種や広告がどう関係するのかなどに関心がある人など、予備知識ゼロでも読める内容と自負しているので、広くご笑覧いただければ幸いです。

ところで、本章では特にマス・メディアの内容分析研究の知見を踏まえて、エスニックマイノリティ（在日外国人を含む）の表象について議論しているのですが、執筆にあたって先行研究を整理していると、エスニックマイノリティ一般はともかく、日本における外国人のメディア表象に関する内容分析的研究をup-to-dateかつsystematicに整理した文献がみあたらず[^1]、自分で相当部分を整理せざるをえませんでした。そのさいに、可読性を重視して表形式で文献を整理していたのですが、紙幅の都合上、それ自体を掲載することはできませんでした。ただ、この種の論点に対する学生の関心が――（常勤講師としての経験則にもとづくかぎりですが――（い点、また私自身今後も内容分析的研究を推進するなかで多分何度も参照すると考えられる点を踏まえ、このまとめを公開することにしました。選定の基準は以下の通りです。当たり前ですが、あくまで有賀が現時点で把握しているものにとどまり、網羅的でも系統的でもないので、参考資料としてのみお使いください。

[^1]: 部分的な例外として、日吉（2008）、渋谷（2021）がある。

-   データの形態がマス・メディア（テレビ、雑誌、新聞）上の広告であること。
-   観察対象が「外国人」と明示的に指定されている、もしくは変数として「日本人」「外国人」「白人」などのカテゴリーが用いられていること。
-   査読論文ないし書籍として刊行されていること。

| 文献            | データ                                                          | 知見                                                                                            | 備考 |
|----------------|---------------------|-------------------|----------------|
| 諸橋 (1989)     | 1986年の『主婦の友』『non・no』『Cosmopolitan』の各誌の広告記事 | 日本人の占める割合は約6割で、残りの4割は白人ないし白人系ハーフであった                          |      |
| 川竹ほか (1992) | 日本その他アジア諸国計7カ国のテレビCM                           | 日本では他国よりも外国人とりわけ白人の起用率が高く，化粧品・酒類・飲 料などのCMで登場頻度が高い |      |
| 3               |                                                                 |                                                                                                 |      |
| 4               |                                                                 |                                                                                                 |      |
