---
title: "【試験版】社会科学系の初年次教育で学生に紹介するおすすめのジャーナル"
date-modified: last-modified
date-format: "YYYY-MM-DD"
---

# 背景と目的

大学の学部1年生を対象にした初年次教育では、文献検索の実習は、レポートやプレゼンの作成とならんで、必須項目といっていいだろう。しかし、実際に2年ほどやってみると、検索してみてもあまりノウハウが得にくい、厄介な問題にいろいろと直面する。

そのひとつに、学生が収集するがソース、ジャーナルによって玉石混交になりがちであるという問題がある。とくに厄介なのが、オープンアクセス状態の卒論や査読なし紀要論文である。google scholarやjstageを使ってもこの問題は解消できないし、学生の検索スキルにかかわらず、「検索ガチャ」によって成果物の質が左右されるのは好ましくない。

以上の考えのもと、このエントリでは、「とりあえず検索するときにこのへんのソースは信頼できる可能性が高いよ」「検索するときにこのへんをジャーナル名でいれるとよいよ」というのを紹介することにした。当然だが、1人の社会学ポスドクの独断と偏見、および担当授業の性質にもとづくチョイスであり、網羅的でも体系的でも汎用的でもない。なお作成にあたっては麦山亮太先生（学習院大学）の[ご教材](https://ryotamugiyama.github.io/seminar_sociology_r/plan.html#:~:text=%E3%81%82%E3%82%8B5%E3%80%82-,%E7%A4%BE%E4%BC%9A%E5%AD%A6%E8%A9%95%E8%AB%96,%E6%97%A5%E6%9C%AC%E5%8A%B4%E5%83%8D%E7%A0%94%E7%A9%B6%E9%9B%91%E8%AA%8C,-%E7%90%86%E8%AB%96%E3%81%A8%E6%96%B9%E6%B3%95)を参考にさせていただいた。そのうち誰かのコメントや有賀の意見変更があれば加筆修正するかもしれない、永遠の試験版である。

# おすすめのジャーナル

そのまま列挙すると量が多すぎるので、いくつかのトピック別に暫定的に分類した。有賀がとくにおすすめしたいものは太字にしている。また注意点が必要なものは下の階層で補足している。なおリンクはいちおうすべて貼っているが、直接アクセスするのではなく、大学の検索システムやgoogle scholarで検索するときに他のキーワードとジャーナル名を入れたほうが効率的に検索できるだろう。

## 全般

-   [社会学評論](https://www.jstage.jst.go.jp/browse/jsr/-char/ja)
-   [理論と方法](https://www.jstage.jst.go.jp/browse/ojjams/-char/ja)
-   [**人口学研究**](https://www.jstage.jst.go.jp/browse/jps/-char/ja/)
    -   分析的には高度だが、トピックがホットなものが多いので、比較的参考になるだろう。
-   [**『放送研究と調査』**](https://www.nhk.or.jp/bunken/book/monthly/backnumber.html)
    -   ISSP（国際比較調査）の結果や簡易な分析結果が報告されており、トピックも知見も非常に幅広く平易にまとまっているため、有益である。
-   [SSM調査報告書](https://www.l.u-tokyo.ac.jp/2015SSM-PJ/report.html)
    -   この文献は厳密にはジャーナルではないので、論文検索システムで検索してもヒットしません。使用するときにはGoogle 検索か公式サイトを使い、引用するときは教員に聞いてください。
-   [**日本労働研究雑誌**](https://www.jil.go.jp/institute/zassi/index.html)
    -   内容が比較的平易かつタイムリーなものが多い。個人的には教育・家族・労働・階層などのトピックに関係するものとしてはとくに一押し。出版元であるJILPTの公式サイトで他の報告書と横断で検索するのも良いだろう。
-   [年報社会学論集](https://www.jstage.jst.go.jp/browse/kantoh/-char/ja)
-   [ソシオロジ](https://www.jstage.jst.go.jp/browse/soshioroji/-char/ja)
-   [フォーラム現代社会学](https://www.jstage.jst.go.jp/browse/ksr/-char/ja)

## 家族・仕事

-   [**家族社会学研究**](https://www.jstage.jst.go.jp/browse/jjoffamilysociology/-char/ja)
    -   家族関係のトピックが豊富である。バックナンバーを見るだけでもヒントにはなるだろう。
-   [NFRJ18報告書](https://nfrj.org/nfrj18publishing.htm)
    -   この文献は厳密にはジャーナルではないので、論文検索システムで検索してもヒットしません。使用するときにはGoogle 検索か公式サイトを使い、引用するときは教員に聞いてください。バックナンバーを見るだけでもヒントにはなるだろう。
-   [**生活経済学研究**](https://www.jstage.jst.go.jp/browse/seikatsukeizaigaku/-char/ja)
    -   家族・労働関係のトピックが豊富である。バックナンバーを見るだけでもヒントにはなるだろう。
-   [**家計経済研究**](https://kakeiken.jp/old_kakeiken/jp/journal/jjrhe/index.html)
-   [**NWEC実践研究**](https://www.nwec.go.jp/about/publish/journal.html)
    -   ジェンダーに関する最新動向と基本的学術的知見の整理が参考になる。バックナンバーを見るだけでもヒントにはなるだろう。
-   [**労働政策研究報告書**](https://www.jil.go.jp/institute/reports/index.html)
    -   労働研究関係の調査報告書がいろんなトピックで書かれている。出版元であるJILPTの公式サイトで他の報告書と横断で検索するのも良いだろう。
-   [**調査シリーズ**](https://www.jil.go.jp/institute/research/index.html)

## 教育

-   [**教育社会学研究**](https://www.jstage.jst.go.jp/browse/eds/-char/ja)
-   [**教育学研究**](https://www.jstage.jst.go.jp/browse/kyoiku/-char/ja)
    -   教育の問題に関して非常に幅広く扱われている。
-   [日本教育社会学会大会発表要旨集](https://ci.nii.ac.jp/ncid/AA11714117)
