---
title: "共著論文を共同執筆するための簡単な10のルール"
author: "yaaruga"
date: "2024-05-24"
categories: [Tips]
format: html
---

**Frassl, Marieke A., David P. Hamilton, Blaize A. Denfeld, Elvira De Eyto, Stephanie E. Hampton, Philipp S. Keller, Sapna Sharma, Abigail S. L. Lewis, Gesa A. Weyhenmeyer, Catherine M. O’Reilly, Mary E. Lofton, and Núria Catalán. 2018. “Ten Simple Rules for Collaboratively Writing a Multi-Authored Paper” edited by F. Lewitter. *PLOS Computational Biology* 14(11):e1006508. doi: [10.1371/journal.pcbi.1006508](https://doi.org/10.1371/journal.pcbi.1006508).**

# 背景

-   初めて共著論文の筆頭著者という役割を担うことになったので、‎Geminiに参考になる論文を教えてくれと頼んだら入手した論文。
-   生物学系のジャーナルなので分野としては無縁だが、科学一般の共著の一般的規則を定式化したものとして参考になりそうなので、読んでみた。

# 内容

著者らは、自分たちのこれまでの共著論文の執筆の経験を踏まえて、以下の10の規則を提案している。

1.  **執筆チームを賢く作る**
    -   「研究プロジェクトの最初の目標を確認し、論文に対す る全員の期待を集め、チームメンバー全員が論文執筆に参加 するかどうかを決めるのがよい方法だ。この段階は通常、研究プロジェクトのリーダーが始める。執筆チームを任命する際は、チームが論文執筆に必要な専門知識を兼ね備えていることを確認し、必要であれば新しい人を加えるオープンな姿勢を保つようにしよう。」 [@frassl2018: 2]
    -   書記、リーダー、ファシリテーターなどの役割を配分することで、著者の関与を保持し負担を分担することができる

<!-- -->

2.  **主導権を握るならリーダーシップを発揮する**
    -   執筆工程をリードし、出版までの作業工程を監督・管理し、適切な意思決定を遂行すること
    -   メンバーの声を平等に聞きつつ、原稿の構造や内容などを適宜取捨選択すること。
    -   会議の進行役を任せたり、原稿のセクションごとに責任者とサブリーダーを割り当てたりするなど、仕事を任せたり分担したりするタイミングを心得ていること

<!-- -->

3.  **データ・マネジメント・プランを立てる**
    -   複数著者による論文は、多くの場合、様々な情報源やデータ提供者から得られた大規模なデータセットを使用したり、作成したりする。
    -   プロジェクトデータをどのように共有し、バージョン管理し、保存し、管理するか、また、出版中および出版後にチーム内の誰が（生）データにアクセスできるかの方針を決めること
    -   プランにメンバーが正確に従うことが必要である

<!-- -->

4.  **オーサーシップ・ガイドラインを共同で決める**
    -   特定のガイドラインを作成して著者の内訳と順序を決定すること

<!-- -->

5.  **執筆戦略を決める**
    -   チームのニーズ、外的要因にあわせて執筆戦略を策定すること。
    -   役割をセクションごとに分担しつつ、全員が全体の構造やフォーマットの決定に関与すること。

<!-- -->

6.  **ニーズに合ったデジタルツールを選ぶ**
    -   バージョン管理、コメント、変更履歴の確認に関するプランを前もって作成し、適切なツールを運用すること。
        -   「グループ全体が一緒に執筆するプロジェクトでは、Google DocsやOverleafのような同期技術は、バージョン管理を容易にするインタラクティブな執筆を可能にすることでうまく機能する。対照的に、逐次的に書かれた論文、サブセクションごとに並行して書かれた論文、または一人の著者によってのみ書かれた論文では、Microsoft WordやLibreOfficeのような従来のプログラムを使用することができる。」[@frassl2018: 4]
    -   ツールは利用可能性、使いやすさ、コスト、分担の仕方などに合わせて決めること。
    -   良質なコミュニケーションは論文の質にも反映される。

<!-- -->

7.  **明確なスケジュールを設定し、それを守る**
    -   まず最初の最終的な締切を確定しそれを遵守すること。そのうえでタイムライン・工程を策定すること

<!-- -->

8.  **プロセス全体を通して透明性を保つ**
    -   締切や役割分担を透明にすることで誤解や対立を避ける
    -   会議の記録を残したり、フィードバックや連絡、相談をきちんとしてもらうことで、問題が生じたり、生じても解消できるようにする

<!-- -->

9.  **公平性、多様性、包摂性を育む**
    -   共著論文は著者の属性や背景が多様である
    -   著者の多様性を強みにするためにはメンバーの文化的多様性を尊重し対等な立場になることを強調することが大事である

<!-- -->

10. **共著の倫理的意味を考慮する**
    -   共著者はいずれもなんらかの形で著作への責任を負う

    -   記述やデータにはいずれも正確を期り、適切な確認の段取りを踏む必要がある

以上を踏まえた結論として以下のように述べている。

> 「私たちは、多様なグループで研究することの利点は、多くの人々を調整するための取引コストを上回り、アプローチの多様性、斬新な科学的成果、そして最終的にはより優れた論文を生み出すと信じている。チーム・サイエンスのプロジェクトに好奇心、忍耐力、開放性をもたらし、配慮と共感を持って行動することができれば、特に論文を書くときには、その経験は楽しく、生産的で、やりがいのあるものになるだろう。」 [@frassl2018: 7]

------------------------------------------------------------------------

# 感想

特別に目新しい知見はないけれどはないけれど、あらためて「共著論文を書くときに意識すべきこと」ってなんだっけ？という問いに直面したときに、一般的な指針を与えるものとして適宜参照する価値のある論文だと思う。
