---
title: "朝日新聞の取材記事に関する補遺"
author: "yaaruga"
date: "2024-04-17"
categories: [Teaching, Media]
---
2024年2月28日に朝日新聞 Re:Ron に私への取材にもとづく記事[「「ハーフ」当事者たち、差別経験の語られ方　SNS分析で見えた葛藤」](https://www.asahi.com/articles/ASS2V44NRS2NULLI004.html)が掲載されました。私自身の研究や社会科学の知見をもとに、いわゆるハーフ／ミックスの人々の経験する偏見や排除、人種主義やアイデンティティについて話しました。

本文では言及できなかったので、今回の記事の発言にあたって参照した文献を以下のポストでご紹介します。

## SNSとハーフとしての発信について

今回の記事では、ハーフの若者を事例として、マイノリティが自らの偏見や差別や生きづらさを発信することが困難であることについて話していますが、これは私自身がこれまでソーシャルメディアデータの量的・質的調査を通じて取り組んできた論点です。

拙論[「「ハーフ」は偏見・差別経験をいかに語りうるのか」](https://researchmap.jp/ya-ruga/published_papers/36759755)および[「アスリートとしての反レイシズム実践とそのジレンマ」](https://researchmap.jp/ya-ruga/published_papers/42824621)では、それぞれ会話分析や談話心理学といったアプローチをつうじて、外国にルーツをもつ若者が自らの差別や偏見を受けた経験を発信したり、あるいは社会問題としてのレイシズムに言及するにあたって、どのようにそのオーディエンスとの関係を調整しているのか、特に差別や偏見やレイシズムをめぐる道徳的な葛藤を回避・低減するためにどのようなことをしているのかを分析しています。

マイノリティにとって、マジョリティとしての聞き手や読み手に取り巻かれる状況のなかで、差別や偏見の経験を語ることには固有の困難があります。そしてかれらは、実に豊穣な資源と多様な方法を駆使して、その困難に対処しています。そうした実践はそれ自体として差別という現象を理解するうえできわめて重要なものです。そうしたかれら自身の実践のあり方、そしてそれを明らかにするための学的営みのあり方に関心を持たれた方は、上の拙論はもちろん、そのなかで引用している文献にもぜひ目を通して見てみてください。

また拙論[「だれが「ハーフ」としてソーシャルメディア上で語るのか」](https://researchmap.jp/ya-ruga/published_papers/42475922)では、TikTok上における「ハーフあるある」という文字列を含む投稿の投稿者の属性を分類し、集計しています。主要な知見として、それがマス・メディアよりもハーフの人種的多様性を反映している――たとえば黒人系やアジア系やラテン系といった白人系よりもはるかに周縁化されてきたとされる人々――一方、中国系や韓国系といった人口の大部分を占める東アジア系ハーフが周縁化されていること、その点では「ハーフ」というカテゴリーが身体的・外見的差異を前提としながらソーシャルメディアでも機能していることを示しています。ソーシャルメディアがマスメディアと比較してどのようにマイノリティのエンパワメントや連帯の資源を提供するのか、しないのかという論点はまだまだ実証的知見が必要な論点で、今後もいろいろな手法で取り組んでいこうと思っています。

## 「日本人の条件」について

記事で私は国籍・文化/民族・人種/血統が日本人らしさの条件であると言っていますが、これは日本の社会学では長らく議論されてきた論点です。関連する研究は多岐にわたりますが、代表的な成果として、日本ではこれらの単位が混同されがちであること、「日本人」なる表現がそれらを多義的かつ柔軟に指し示す多元的な概念として機能していることが論じられてきました（福岡 1993; Lie 2001; Liu-Farrer 2020; 杉本・マオア 1995）。

また近年ではこうした議論を踏まえた実証研究も進展しており（五十嵐 2015; 石田 2016; 田辺 2019; Woo 2022）、どのような属性が「日本人の条件」として重視されているのかが検証されています。そして本人の国籍や自己理解とならんで、親の国籍や血統が重要視されていることなどが明らかになってきています。

また本文では若い世代においてこうした認識に変化があることを楽観しているとも言っていますが、これはいくつかの継続的全国調査の知見をふまえたものです。たとえば15年近く継続されている「国際化と市民の政治参加に関する世論調査」の結果をみると、日本人の条件として「先祖」を重視する傾向は長期的に弱まりつつあり、特に若年層ではその傾向が弱いことがわかっています（国際化と政治参加に関する研究プロジェクト  2022）。また若年層において外国人への寛容な態度がより広がっていることも示されています（岡田 2020; 田辺 2019）。^[もっとも、こうした傾向が年齢効果（一般に若い人ほど寛容であるだけで高齢化とともに不寛容になる）によるのか、コーホート効果（ある特定の時代に生まれた人たちが一般に寛容である）によるのかはよくわかりません。]

## 多元的アイデンティティについて

マジョリティのマイノリティに対する、より特定的には非移民の移民的背景をもつ人々への寛容性を増やし、偏見や敵意を減らすにはどうすればいいかという点については膨大な量の社会学・心理学・政治学の知見があります。一方で増大の要因についていえば、移民を自分たちの資源に対する脅威として認識すること――たとえば移民によって治安や雇用や文化が脅かされるというように――が移民への敵意を増大させるという集団脅威理論という理論にもとづく研究が広く行われています。

また最近では移民の否定的側面――移民による犯罪など――に関する報道への接触が移民への敵意を増大させることも明らかになっています（李 2009; Damstra et al. 2019; Schlueter and Davidov 2013）。特にメディアは、日本のように外国ルーツの人が少ない社会ではかれらについての情報源として重要な影響力をもっている可能性もあります（五十嵐 2019）。

他方で移民の偏見の減少の要因としては、特に有名なのは集団間接触理論というもので、異なる集団の成員が一定の条件のもとで接触することで偏見や敵意が減るというものです。これについてはあまりにも膨大な文献があり、有名でもあるので、今回の記事では触れませんでした。代わりに触れたのが多文化主義や多元的アイデンティティといった視点です。近年の心理学では、膨大な量の既存の知見を踏まえたメタ分析が行われており、人々が複数のアイデンティティをもつ存在であると認識すること（Verkuyten and Yogeeswaran 2020）、異なる文化や民族の間に対等な関係を想定していること（Whitley et al. 2019）が、偏見や敵意を有意に減少させることが明らかになっています。

ちなみに先程メディアの影響に言及しましたが、同時に注意すべきは、近年ますます存在感を増しているソーシャル・メディアと世論の関係です。私たちはしばしばソーシャル・メディアを通じてある特定のトピックやイベントについてSNSで誰かが何を言っているかを見ることで、そこに世論を観察しようとすることがあるでしょう。そして外国にルーツをもつ人をめぐる発言もまたそうした仕方で観察されることがあるでしょう。
ただし、こうした私たちがついとってしまいがちな姿勢――ソーシャル・メディア上の特定のトピックをめぐる言論の状態を実際のそのトピックをめぐる世論の兆候や指標として受け止める姿勢――にはかなり慎重になる必要があります。世界的な計算社会科学の権威であるC. Bailは、豊富な実証的研究にもとづいて、ソーシャル・メディア上では実際の世論よりも過激な意見が過剰に顕在化する傾向があること、利用者もまたそうした傾向ゆえに穏健的・中庸的な意見を過小に見積もる傾向があることを示唆しています（Bail 2021）。また日本でも安倍晋三元首相に対するTwitter上の投稿を大規模に分析した研究によって、Twitter上で表現される安倍首相への感情が世論と乖離していることを示唆しています（永吉ほか 2021）。ソーシャル・メディアとマイノリティへの意識の関係を考えるにあたっては、前者が後者に与える影響力が強いことだけでなく、後者の一般的傾向が必ずしも前者に「正確に」反映されているとは限らないことに注意することが必要といえるでしょう。

## 引用文献（フォーマットはZoteroで自動生成したためテキトーです）

Bail, Christopher. 2021. Breaking the Social Media Prism: How to Make Our Platforms Less Polarizing. Princeton: Princeton University Press.

Damstra, Alyt, Laura Jacobs, Mark Boukes, and Rens Vliegenthart. 2019. “The Impact of Immigration News on Anti-Immigrant Party Support: Unpacking Agenda-Setting and Issue Ownership Effects over Time.” Journal of Elections, Public Opinion and Parties. doi: 10.1080/17457289.2019.1607863.

福岡安則. 1993. 在日韓国・朝鮮人――若い世代のアイデンティティ. 中央公論社.

李容玲. 2009. “日本人と外国人の共生を促す決定要因について――JGSS-2005 データに反映する制度と意識の相関性.” 日本版 General Social Surveys 研究論文集 (8):121–40.

Liu-Farrer, Gracia. 2020. Immigrant Japan: Mobility and Belonging in an Ethno-Nationalist Society. Ithaca: Cornell University Press.

永吉希久子・瀧川裕貴・呂沢宇・下窪拓也・渡辺誓司・中村美子. 2023. “ソーシャルメディア言論分析の方法②――安倍首相に対するTwitter上の投稿分析を事例としてトピックモデルの適用.” 放送研究と調査 73(4):70–85. doi: 10.24634/bunken.73.3_70.

岡田真理紗. 2020. “外国人増加への期待と不安――「外国人との共生社会に関する世論調査」から.” 放送研究と調査 70(8):78–87.

田辺俊介. 2019. “ナショナリズム――その「高まり」は本当か.” Pp. 22–43 in 日本人は右傾化したのか――データ分析で実像を読み解く, edited by 田辺俊介編著. 勁草書房.

五十嵐彰. 2015. “「日本人の条件」に対する一般的イメージ――Mokken Scale Analysis による条件の重要性の順位の検証.” 理論と方法 30(2):293–306. doi: 10.11218/ojjams.30.293.

五十嵐彰. 2019. “排外主義——外国人増加はその源泉となるか.” Pp. 94–136 in 日本人は右傾化したのか――データ分析で実像を読み解く, edited by 田辺俊介編著. 勁草書房.

石田淳. 2016. “『日本人』の条件――インターネット調査データを用いた社会的カテゴリー分析.” 社会学評論 67(2):182–200. doi: 10.4057/jsr.67.182.

Lie, John. 2001. Multiethnic Japan. Cambridge, Mass: Harvard University Press.

Schlueter, Elmar, and Eldad Davidov. 2013. “Contextual Sources of Perceived Group Threat: Negative Immigration-Related News Reports, Immigrant Group Size and Their Interaction, Spain 1996-2007.” European Sociological Review 29(2):179–91. doi: 10.1093/esr/jcr054.

杉本良夫・ロス・マオア. 1995. 日本人論の方程式. 筑摩書房.

Verkuyten, Maykel, and Kumar Yogeeswaran. 2020. “Cultural Diversity and Its Implications for Intergroup Relations.” Current Opinion in Psychology 32:1–5. doi: 10.1016/j.copsyc.2019.06.010.

Whitley, Bernard E., and Gregory D. Webster. 2019. “The Relationships of Intergroup Ideologies to Ethnic Prejudice: A Meta-Analysis.” Personality and Social Psychology Review 23(3):207–37. doi: 10.1177/1088868318761423.

Woo, Yujin. 2022. “Homogenous Japan? An Empirical Examination on Public Perceptions of Citizenship.” Social Science Japan Journal 25(2):209–28. doi: 10.1093/ssjj/jyac001.

