---
title: "【文献】Joppke (1998) 「国民国家を問い直す移民」"
author: "yaaruga"
date: "2024-04-16"
categories: [Imput, Teaching, Immigrant, Ethnicity/Race, Quotes]
---
**Joppke, Christian. 1998. “Immigration Challenges the Nation‐State.” Pp. 5–47 in *Challenge to the Nation-State: Immigration in Western Europe and the United States*, edited by C. Joppke. New York: Oxford University Press.**

## 内容

欧米諸国の出入国・移民統合政策の比較政治学的研究の大御所であるChristian Joppkeが編者を担当した本に書いた序論。

特に20世紀後半に欧米諸国における出入国・移民統合政策の概略を論じている。

## 感想

特に目新しい知見はないし、著者の英語は他の移民研究者と比較すると読みにくいほうだと思うが（特にボキャ貧には単語が難しい）、理論的知見の整理と著者一流のquotableな名文が非常に印象に残る。こういうの非常勤とか論文の結論で使いこなせたらカッケーなーと思う。

:::{.callout-note}
## 同化主義と多文化主義
「歴史的に、移民は国民の一員になること、すなわち受入社会の共通文化へと「同化」することを期待されていた。西洋諸国をつうじて、その期待は「多文化主義」による挑戦を受けている。［中略］多文化主義は同化の拒絶である。多文化主義は国民国家の根本原理に挑戦するものである。それは政治的境界と文化的境界の合一という原則である。」（Joppke 1998: 31）
:::

:::{.callout-note}
## 反植民地主義と多文化主義
「反植民地主義は最初の近代的アイデンティティ政治であった。それは否定される必要のある外からの侵略への反応であったがゆえに、反植民地主義の主眼は統合ではなく分離であった。アイデンティティと差異へのこうした焦点化は多文化主義によって活用された。それは反植民地主義の一般化された形態とみなすことができるかもしれない。そもそも戦後移民受入れの新奇性は、その起源が主に旧植民地と第三世界の諸国にあったという点にある。このかぎりでの移民受入れは反転した植民地主義であり、文化的差異の政治を近代世界システムの周縁から中核へと持ち込むものであったとみなすことができるかもしれない。」（Joppke 1998: 32）
:::
