---
title: "【文献】Bail (2021) 『ソーシャルメディア・プリズム――SNSはなぜヒトを過激にするのか?』"
author: "yaaruga"
date: "2024-05-09"
draft: true
categories: [Imput, Social media, Teaching, Media]
---
Bail, Christopher. 2021. **Breaking the Social Media Prism: How to Make Our Platforms Less Polarizing**. Princeton: Princeton University Press.（松井信彦訳，2022，『ソーシャルメディア・プリズム――SNSはなぜヒトを過激にするのか?』みすず書房.

## 内容

計算機社会科学の先端的研究を多く手掛けていることで知られる著者がソーシャル・メディア・プラットフォームにおける政治的分極化の実態やメカニズム、対処方法について非専門家向けに論じた本。みすず書房から[翻訳書](https://www.msz.co.jp/book/detail/09083/)が出ている。

まず第1章では、本書の基本的な目的と背景が説明される。特に、ソーシャル・メディアを、たんなる特定の種類の情報や意見によってユーザーを分断させるものとしてではなく、むしろ人間の自他のアイデンティティに対する理解を歪曲するものとして捉える視点を提起している。

> 「社会的孤立が進む時代においてソーシャルメディアプラットフォームは私たちが自己を――そして互いを――理解するために使う最重要ツールのひとつになってきた。私たちがソーシャルメディアにやみつきなのは、目を引く派手なコンテンツが表示されたり気を散らすコンテンツが延々と流れてきたりするからではなく、人間の生得的な行動、すなわち、さまざまなバージョンの自己を提示しては、他人がどう思うかをうかがい、それに応じてアイデンティティを手直しするという行動を手助けしてくれるからである。ソーシャルメディアは、社会を俯瞰するのに使える巨大な鏡ではなく、各自のアイデンティティを屈折させるプリズムなのだ——それによって私たちは、互いについて、そして自分についての理解をゆがめられてしまう」（=11-12）

### 2 Why Not Break Our Echo Chambers? 12-

第2章以下は、本書の上述した主張を支える知見を提供する分析が実際に紹介されていく。
エコーチェンバー（自分と似た意見ばかりを見ること）が分極化を促進するのかを明らかにするため、異なる政治的意見をもつユーザーをフォローさせると政治的態度がどう変化するのかをみた実験

自分とは異なる政治的意見にふれることは穏健化を促さないばかりか、むしろより極端な態度へと傾くことを促す。

インタビュー（25）

# 3 What Happens When We Break Them? 26-

実際に実験に参加したユーザーへのインタビューから、自分と異なる意見がどのように受け止められているのかを検証していく

# 4 The Social Media Prism 41-

```
ソーシャルメディアは「プリズム」である
一方でそれは、政治的に過激な意見を表明するユーザーにとって親和的な意見への接触を可能にすることでその意見を正常化する
他方でそれは、異なる意見をもつ人びとをより極端に異質に見せる
その結果、実際の政治的態度と認識される態度とのずれを生み、穏健な意見を見えなくして見かけ上の分極化を生み出す
```

- 「人が自尊心を高めるアイデンティティを養成することはこれまでの研究で判明しているが、そのために他人が発する信号をどう読み取っているのかは分析されていない。この分析には社会学が不可欠だ。社会学は社会的関係の科学である。社会学はどのように社会的文脈が人々の信念、行動、そして...アイデンティティを形づくるのかを研究する。」（49）
    
- ソーシャルメディアの特性は対面的相互行為よりもはるかに柔軟かつ統制力をもって自己呈示をすることを可能にする点にある（50f）
    
    - 「自己呈示に対するさらなる制御力を与えてくれるだけでなく、ソーシャルメディアは、私たちのおかれている社会的環境のかなりの部分をかつてないほどの効率性をもって監視することを可能にもしてくれるのである。…ニュースフィードのおかげで、かつてない規模と速さで社会的比較ができる。」（51）
        
- 「ニュースフィードには社会環境を監視するためのツールが組み込まれている。たいていのソーシャルメデイア・サイトには、自己呈示がうまくいっているかどうかが一目でわかる指標が表示されている。ソーシャルメディア・サイトのアーキテクチャーにはステータスがこうした形ですっかり埋め込まれているのだ。私たちは「いいね」やリツイートやシェアの数をチェックすることで、自分が投稿したコンテンツへの他人の反応が肯定的か否定的かを監視できる。コンテンツが非常に否定的な反応を呼び、他人がわざわざ否定的なコメントを返してくることもある。［中略］ソーシャルメディア・プラットフォームは、各ユーザーのフォロワーや友だちの数を目立つように表示するという形でもステータスを伝えている。ツイッターやインスタグラムのエリートは、それに加えて輝かしい青いチェックマークでVIPとしてのアイデンテイティーが証明され、一方のその他大勢はこうしたプラットフォームをがさつ者の一群のごとく渡り歩かなければならない。」（＝56）
    
- 「ソーシャルメディア中毒のより根源的な原因は、私たちのあまりにも人間的な営みが、ソーシャルメディアによってはるかに簡単にできるようになったことだ。その営みとは、さまざまなアイデンテイティーを試しては他人の反応をうかがい、自己呈示を更新して帰属意識を味わうことである。」（＝57）
    
- 「政治的分極化に重大な影響力を持つソーシャルメディアには、非常に残念な側面がある。社会環境を読み誤りがちという私たちの性向を悪化させることだ。私たちはソーシャルメディア・プラットフォームを、自分の社会的位置づけの把握に役立つ巨大な鏡であるかのように使っている。だが実際には社会環境を曲げたり屈折させたりするプリズムであり、自己や対他人の感覚をゆがめている。ソーシャルメディア・プリズムが最も甚大な影響を及ぼすのは、人がその存在に気づいていない場合だ。」（＝57-8）
    

# 5 How the Prism Drives Extremism 54-

- 過激派はソーシャルメディア上の政治論議において実際の有権者に占めるその比率よりもはるかに大きな影響を有している
    
- ソーシャルメディア・プリズムはが過激派を過激化させる仕組み
    
    1. ソーシャルメディア・プリズムは過激主義を普通化する。
        
        - 「過激主義者が社会的身分を目的としたギャング的振る舞いに深入りするにつれ、交流相手の大半が同じ過潔な意見の持ち主となる。やがて、こうした接触の繰り返しから….彼らの普通ではない見方をたいていの人がしている、と思い始める。」（＝74）
            
    2. 「だがプリズムは過激主義者の自己理解をゆがめるのに加えて、相手方のアイデンティティーをもゆがめる。具体的には、ソーシャルメディア・プリズムは対立党派の人を実際よりも過激そうに見せる。過激主義者が攻撃を仕掛けたとき、応戦相手はえてして相手方の最も過敷な成員だ。こうしてプリズムは、自分の側の過激主義を普通化するのとまさに同じようにして、相手方の過澈主義を誇張する。」（＝74）
        
- 「あいにく、このふたつのゆがみが相まって過激主義のフィードバックループができる。プリズムは、自身の過激主義を合理的だと―あるいは普通だとさえー思わせるのと同時に、相手方をより攻撃的で、過激で、粗野に見せるのである。ソーシャルメディア・プリズムには過激主義者のコミュニティーを生んで維持する力があり、これは深刻な懸念材料だ。」（＝74）
    

# 6 How the Prism Mutes Moderates 68-

認識と現実のあいだのずれが穏健派における政治的無関心を助長し、それがさらにプラットフォームにおける過激派の伸張と穏健派の政治的発信の抑制を助長している

- 政治的関心が強い穏健派はSocMを通じて過激な政治的意見に接触するにつれて自らの意見がその場では受入れられにくいと判断しその場での政治的意見の発信を控える傾向にある
    
- 穏健派の不在は「ソーシャルメディア・プリズムによって生じるもっとも深刻な歪み」（＝90）
    
    - 「一方、ソーシャルメディア・プリズムは相手方を一枚岩で、揺るぎなく、理不尽であるかのように見せる。
        
        過激主義者が私たちの注意を引くのに対し、穏健派はほぼいなさそうに見えておかしくない。穏健派がソーシャルメディアで政治と距離を置く理由はさまざまだ。たとえば、過激主義者から攻撃されたから。あるいは、節度のなさに然とし、そんな言い争いに首を突っ込む意味をほとんど見いだしていないから。ほかにも、政治について投稿すると実生活で苦労して勝ち得たステータスが犠牲になるかもしれず、それが心配で距離をおいている穏健派もいる。過激主義者に反論すればしっぺ返しに遭い、生計や友人関係、あるいは毎年感謝祭で顔を合わせる親戚との関係が崩壊しかねない。穏健派の場合はそうした付き合いがあると、たとえばサラなら、トランプに投票するような輩は誰もが女性を憎んだり性的暴行を大目に見たりしている、とヴィヴィアンおばさんが心底思っているわけではないと知る機会になりうるー犯罪を行ったという確たる証拠もなしにおばさんがトランプの追放を求めていることはやはり受け入れられないにしても。次章で述べるように、あいにくそうした相互理解の機会は社会的孤立が急速に進む時代にあってはきわめてまれだ。共和党派も民主党派もみずからを相手方と異なる郵便番号や娯楽や社会圏に割り振り続けている今、過激主義者に勢いをつけ、穏健派を"ミュート"する、というソーシャルメディア・プリズムの威力は増すばかりで、私は心配だ。」（＝91）
        
- 差別（81）
    

# 7 Should I Delete My Account? 84-

- ソーシャルメディアから離れなれないのはなぜか
    
    - 「若者にとってソーシャルメディアから離れることは、昔ながらの暮らしぶりに戻るだけの話ではなく、自分のライフスタイルを断念することなのだ。」（＝96）
        
    - 特定の社会的紐帯への愛着、家族や同僚からの圧力、企業・自営業者にとってのブランディング
        
    - 「アカウントを削除できない理由として最も重要なのは…ソーシャルメディアは今や私たちの暮らしにすっかり溶け込んでおり、私たちのアイデンティティに影響を及ぼすまでになっていることだ…。Facebook, Twitter、そしてそのほかのプラットフォームは、様々な自己のバージョンを提示すること、それらの自己にほかの人々がどう反応しているのかを監視すること、そしてその反応におうじて自己のさまざまなアイデンティティを改訂することを可能にしている。」（88）
        
- プラットフォーム側の限界
    
    - 検索エンジンのアルゴリズムや一部の悪意ある活動家のプロパガンダ活動が政治的分断を深めているという一般的な主張は必ずしも経験的証拠が得られていない
        
    - 政治的分極化がソーシャルメディアによって助長されているというこれまでの一般的意見に反して、近年の研究はむしろ逆の知見を支持する傾向にある
        

# 8 Hacking the Prism 99-

- 「ソーシャルメディアが偽りの分極化を一気に早めた」（＝111）
    
- ソーシャルメディアと偽りの分極化の間の循環関係を緩和するための3つの戦略（102＝112ff）
    
    1. プリズムを見て取る術を学び、自他のアイデンティティを歪めるというその影響力を認識すること
        
    2. プリズムを通じてじこを観察するすべを学び、自分の行動がプリズムに力を与えることを観察すること
        
        - 「」（＝116）
            
    3. これまでプリズムを助長してきた行動を変容させて相手とより生産的な対話をすること
        
        - 「ある問題についてそれまで賛成していなかったとしても許容できると、あるいは理にかなっていると思える意見の範囲」（＝119）すなわち受容域にある意見と接すること
            

# 9 A Better Social Media 116-

```
より良いソーシャルメディアプラットフォームの構築をつうじてプリズムと分極化の悪循環を断ち切ることもできる
```

- 「…ソーシャルメディア・プリズムは、政治的尺度で最も過激と分類される人を屈折させると同時に穏健派の声を"ミュート"していた。互いを強化するこのふたつのプロセスは、過激主義者を図に乗らせてますます過激な信条を表明させ、穏健派を幻滅させる。そして、大勢の穏健派がそうした過激主義を相手方の典型的な考え方だと誤認するようになる。」（＝130）
    
- 「既存のソーシャルメディア・プラットフォームが前述の原則の数々を導入するのに遅すぎることはない。
    
    フェイスブックやツイッターなどのプラットフォームは、ユーザーのタイムラインに投稿を表示する順序を、単乳なエンゲージメント指標にではなく両党派のユーザーによる承認の数に基づいて最適化することができよう。レコメンダーアルゴリズムについては、各ユーザーの受容域を「いいね」したコンテンツやフォロしているアカウントに基づき特定するよう訓練し、自分と違うが大きくは違わない意見の持ち主とつながようユーザーに促すことができるのではないか。現行のプラットフォームでもこのふたつの改革を組み合せれば、怒させる党派的コンテンツでユーザーを日々刺激するのではなく、妥協の余地のある問題につて相手と関わるようユーザーを後押しするコンテンツをレコメンドすることができるだろう。また、そうた建設的な議論に関わる人向けに新たなインセンティブを用意してもいい。たとえば、評判のユーザーが中党派に訴えるコンテンツをつくっている頻度を示すリーダーボードを用意するのだ。新たなステータスをつくるという手もあるしたとえば、政治以外の達成事項でセレブのステータスを得た人を目立たせるのではなく、多様なユーザーを見事魅了した人を示すバッジを用意するのだ。フェイスブックやツイッターなどの支配的なソーシャルメディア・プラットフォームは、党派の一線を越えたいユーザー向けに自社プラットフォームに新たな場をつくって実験することや、分極化研究所のシミュレーションされたソーシャルメディア・プラットフォームでわれわれがお膳立てしたような、目的を明確にした小規模の対話の機会をユーザーに提供することもできよう。」（＝142-3）
    
      
    
- 「ソーシャルメディアは、様々な自己のバージョンを提示すること、これらのバージョンに他人がどう反応するのかを監視すること、そしてアイデンティティを改訂することを可能にする」（127）
    
- 匿名性のもとでの政治的議題についての会話が政治的分極化を緩和する
    
    - 民主党支持者と共和党支持者どうしをアプリで引き合わせ、チャットで会話をさせた
        

# Appendix: Research Methods 133-

## 感想
読み物としても単純に面白いだけでなく、最先端の手法とデータを組み合わせて直感をある意味では裏づけ、ある意味では反証する知見を提供している良書。

個人的な雑感だが、特に社会学的な話題について学部生のコメントやレポートを読んでいると、特定の意見や現象の経験談としてソーシャル・メディア上
