---
title: "2021年度日本学術振興会特別研究員DC2（社会学専門分野）の申請書を公開します"
author: "yaaruga"
date: "2024-04-11"
date-modified: "2024-04-24"
categories: [Tips, Grant]
---

有賀は2021年に、2022年度日本学術振興会特別研究員DC2（社会学専門分野）に採用されました。研究題目は「「混血児問題」の歴史社会学:戦後日本における多人種性をめぐる実践と経験」です。

DC1では1回、DC2では1回それぞれ落第した経験をへての採用なので、戦歴としてはボロボロです。  ただ3年目になると流石に自分でもノウハウを蓄積できたこともあり、最初に比べると大幅に水準が向上し、なんとか合格することができました。

最近はありがたいことに、申請書の閲覧を希望する方から連絡を受けるようにもなってきました。せっかくなので、より広く社会学専門分野でDCを目指している人の役に立ったらと思い、申請書を公開することにしました。

[2022年度日本学術振興会特別研究員DC2申請書](https://drive.google.com/file/d/10FgoK6DBTt8yvFmAt_uXOHwqMaYjbfE0/view?usp=sharing)

申請書の書き方のノウハウについてはすでにネット上の記事や書籍でかなり広くまとめられているので、付け加えることはありません。経験則として強調したいのは、早く・何度も書くこと、そして何度も添削してもらうことです。私自身、先輩方の手厚い添削がなければ合格は間違いなく実現していませんでしたし、「こうすれば自分の研究内容の要点が伝わるのか」という勘所がつかめるようになったのは、大きな収穫でした。

いま読みなおすとかなり荒削りですし、どこまで・だれの役に立つかもわかりませんが、広い意味でのエスニックマイノリティの研究をしてる社会学分野の人、マイノリティ集団の歴史を研究してる社会学分野の人にはもしかすると何か示唆が得られるかもしれません。

2024-04-24 追記

過去のブックマークを漁っていたら、松浦優さん（九州大学）の[ポスト](https://twitter.com/wrmtw/status/1642919786756849670)でいくつか他の社会学系のDCのtipsや申請書類のエントリがまとめられていたので、以下に列挙します。

- [学振DC2（社会学）の採用内定をいただいて　申請書の書き方など](https://terukisanada.com/dc2/)

- [「学振DC1採用内定獲得に至るまで（雑感）」](https://researchmap.jp/blogs/blog_entries/view/546680/1788632a3f055cdaa3af67db687c67c2?frame_id=1074457)

- [「DC1学振申請書の書き方・コツ・対策（社会科学の補欠繰上合格）」](https://note.com/h_keisuke/n/n8332d72b7308)

- [「学振DC（社会科学）の申請書を公開します」](https://ryotamugiyama.com/blog/2017-02-20-gakushinDC.html)

- [「学振申請書（文系）の書き方（の一例）」](https://tsukasatanihara.hatenablog.com/entry/2019/04/05/133403)