---
title: "一押し文献: Deterding and Waters (2021) 「深層インタビューのフレキシブル・コーディング」"
author: "yaaruga"
date: "2024-04-16"
categories: [Imput, Qualitative research, Methodology]
---
:::{.callout-note}
## 一押し文献
Deterding, Nicole M., and Mary C. Waters. 2021. “Flexible Coding of In-Depth Interviews: A Twenty-First-Century Approach.” *Sociological Methods and Research* 50(2):708–39. doi: 10.1177/0049124118799377.
:::

質的データ（特に質的インタビューとフィールドワークによるethnographicなデータ）の分析を教科書で読むと、たいていこんなことが書いてある。いわく、質的データの分析には量的データの分析のような高度に形式化された手法がない、調査を通じて分析手法を漸進的に設計・考案することが大事である。そして、数少ない標準化された手法として、いわゆるグラウンデッド・セオリー・アプローチが紹介される。あるいは、明示的にそれを採用していないとしても、実質的にそれに近い手法が例として紹介されたりする。もしくは、より分析よりもデータ収集に重点を置いたものなら、そうした分析についての紹介がほとんどないこともあるかもしれない。

「21世紀に入っても、質的研究のトレーニングのほとんどは、1960年代に考案されたグラウンデッド・セオリーに基づいている。」という診断とともに始まるこの論文で、Deterding and Waters (2021) はこうした現状の問題点として、多様な理論的・概念的ツールの候補が存在することを想定していないこと、時間と作業の負担が大きいこと、小規模の質的調査を前提としており、大規模の質的調査データ分析に適していないことをあげている。そしてGTAの理論的仮定がもはや妥当ではないことを確認し、現在の分析的・理論的条件（サンプルサイズの大規模化の必要、既存の理論的知見が豊富であるという前提のもとでの研究プロジェクトの策定...）、技術的条件（CAQDASの発達と普及）に見合った代替的アプローチとして、彼女らのいうフレキシブルコーディングを定式化している。トランスクリプトへ見出しを付与して事例横断的なコードを索出する、データを再読してデータ全体へコードを適用する、コードの妥当性を検証して理論を整備する、という3つの工程がstep by step式に、とても具体的に紹介されている。

Waters先生は移民2世研究、エスニックアイデンティティ論の大御所としてしか知らなかったが、その豊富な分析の経験と理論的知識を踏まえており、著者の現状に対する批判的診断と代替的アプローチの必要性の主張は非常に説得的である。筆者は特に、GTAの時代と異なり現代の質的社会学者は理論的・実質的知識が豊富であるという前提のもとで調査を遂行するのだから、line by lineにトランスクリプトを読んでいくという高度に帰納的な手法は現状に合致していない、また紙とペンと付箋という技術的資源を前提とすることも適切ではないというのももっともな主張である。*Sociological Methods and Research*というトップ・ジャーナルに掲載され、すでに引用件数も3ケタに入っていること、自分のようにある程度の規模で質的調査をやりたい人間にとっておそらく数少ない有望な実行可能な選択肢であることをふまえると、ぜひとも前向きに参考にしたいと思った。

気になった点としては、著者は技術的進歩という前提にもとづいてCAQDASの使用を奨励しているが、それが果たしてどこまで適切なのかということ。現在では特に量的調査の分野ではオープンソース・ソフトウェアの重要性が（再現性との関係で）示唆されているように思う^[Trilling, Damian, and Jeroen G. F. Jonkman. 2018. “Scaling up Content Analysis.” Communication Methods and Measures 12(2–3):158–74. doi: 10.1080/19312458.2018.1447655.]。筆者らはAtlas.tiとNvivoを使っているけれど、それらは商用ソフトなのでこの問題を解決しない。もっともこの点は、「RやPythonで質的データのマニュアルコーディングを効率的に行えるのか」という別の問題につながる上に、その問題についてはあまり議論が進んでいるようには見えないので、根深い問題なのかもしれない。

:::{.callout-note}
## 現代社会学の理論的トレンドに見合った方法としてのフレキシブル・コーディング
「現代社会学がメカニズムを記述することを特権としていることを踏まえ、今日、多くの社会学者が、回答者のグループ間や調査場所間のコントラストを強調するように研究をデザインしている。仮説に基づく顕著な差異にまたがって研究をデザインすることで、学者たちは文脈と概念の関係を明らかにする議論を構築することができる。このアプローチでは、グループや調査地による違いのパターンを確立するために、それぞれの「セル」に十分な数の回答者が必要となる。この方法で設計された研究では、大量のテキストデータが作成されるため、分析段階で研究者にロジスティクス上の課題が生じる。我々は、グループの違いの輪郭を調べる研究は、以下に概説するコーディング手順に特に適していると考えている。」（Deterding and Waters 2021: 719）
:::
