---
title: "【文献】盛山和夫 (2008)「社会調査にとって本当の課題はなにか」"
author: "yaaruga"
date: "2024-04-20"
categories: [Imput]
---
**盛山和夫，2008，「社会調査にとって本当の課題はなにか」『社会と調査』 1(1): 6–12.**

## 内容

社会調査協会の公式ジャーナル『社会と調査』 創刊号の冒頭を飾った論文。題名通り、現時点で学術的な社会調査の直面している課題を概括している。その内容そのものはそれほど特異ではないのだが、特に後半では日本社会学一般の問題点を概括していて、興味深い。

筆者は、「マス・メディア的な関心や地平のレベルでの「発信」という点では，今日の日本における社会学系のプレゼンスはけっして小さくはない」一方、「こうしたプレゼンスの高さは、必ずしも学問の発展と結びついてはいない」ことを指摘する（9）。そのうえで「社会学系の学問が他と比べてより多 く抱えている問題
」を2つあげている（9f）。

第一に、「国際性の弱さ」である。社会科学一般で今日この課題は指摘されているが、社会学では特にその試みが遅れているという。
第二に、「革新性の低さ」である。筆者によると現在の日本の社会学者の間では、「個々の研究において探求しようとしている課題が、その学問領域の学術の発展にとってどのような意味をもち、課題の達成によってその水準をどの程度引き上げることになるかについての明確な自覚も他者からの評価も乏しい」（9）。「ホームレスの人々となんとかラポールを形成して、その人たちのライフヒストリーや置かれている問題状況を明らかにしました」「ある農村の共同性の衰退を確かめてきました、あるNGOの活動を調査してきました」のような事例研究、「教育機会の階層格差が増えたか減ったか，所得格差が増えたか減ったか，という ような事実探求だけをめざした統計的調査研究」は増えている一方、それらは「自らの経験的な調査研究によって、学問の理論および概念図式レベルでどのような革新が促されることになるのかについての問題関心がまったく欠落している」（9）と批判している。

これらをまとめて筆者は、「国際性の弱さと革新性の弱さは、社会調査に限らず社会学系の研究全般に共通する深刻な問題状況なのだが，そのことは、社会調査の意義を世間に向けて訴えかける上で最大の障碍になっている」（10）と整理している。

こうした現状診断を踏まえて筆者は「国際性の弱さと革新性の弱さ」はいずれも「いかなる研究が学術の革新に貢献しているかについての国際的な共通認識の欠如」に起因していると評価している。こうした「自らの研究が国際レベルでの学術の進展にとってどういう貢献をなすものであるか」という問題関心の完全な欠落」が「ピア・レビューの欠如」あるいは「同業仲間の仕事への関心の欠落」をもたらし、ひいては「国際性の弱さと革新性の弱さ」という事態を招いている、というのが筆者の見立てである（11）。そしてこうした事態を是正するためにピア・レビューの強化、それによる「適切なレビュー」の充実化を提案している。

## 感想

この論文が書かれたのは2008年だが、問題提起の内容には、およそ古さを感じない。個人的には、「同業仲間の仕事への関心の欠落」の徴候として、質的調査に典型的な「国内の先行研究しか参照していないケース」と、量的調査に典型的な「論文のテーマに関わる先行研究として欧米のものだけを挙げて，国内のものをほとんど無視するというケース」が挙げられていることが興味深かった。

2024年現在からみれば、この論文は小熊英二の論文^[Oguma, Eiji. 2021. “Sociology of the Japanese, by the Japanese, for the Japanese: A Short History of Unintentional Indigenization of Sociology in Japan.” *International Sociology* 36(5):684–96. ]とセットで読まれるべきだと思う。小熊は端的に「日本人の、日本人による、日本人のための社会学」と定式化し、日本社会学は越境的な学的共同体というよりも国内の公衆を包含する読者共同体を対象として発展してきたと示唆しているが、その経緯を踏まえれば盛山の指摘する問題もすべて説明できると思う。ちなみに小熊論文において盛山論文は引用されていない。

J社会学の国際化という大きな学問的課題はここで取り上げるのにはあまりにも大きい問題で、学会でもそれに特化したセッションが組まれているくらいである。個人的にもかなり重大な問題なので、そのうちより丁寧に再論してみたい。

:::{.callout-note}
## 日本社会学の一般的課題
「ピア・レビューの欠如あるいはレビューの偏りは，われわれの学問共同体が抱えている深刻な問題状況を端的に表している。それは単純化して言えば「どういう研究が研究水準を革新するものであるか」に関する価値標準の喪失である。これはしかし逆に見れば、「適切なレビュー」の提示を心がけていけば，おのずからそうした価値標準の構築に取り組むことになることを意味している。さらに、ピア・レビューの強化は、同じ領域に携わる国内の研究者の間での（競争と協力とからなる） 共同性の構築と、それを梃子とする国際性の向上にとって不可欠の要件である。」(盛山 2008: 11)
:::
