---
title: "【文献】外村大（2010）「朝鮮人労務動員をめぐる認識・矛盾・対応」"
author: "yaaruga"
date: "2024-04-24"
categories: [Input, Immigrant, Ethnicity/Race, Teaching, Korean]
---
**外村大，2010，「朝鮮人労務動員をめぐる認識・矛盾・対応――一九三七～一九四五年」黒川みどり編著『近代日本の「他者」と向き合う』部落解放・人権研究所，200–226．**

## 内容

在日朝鮮人史研究の大家である筆者が戦時中の朝鮮人労務動員の経過を概括した論文。

## 感想

論集そのものが近代日本のマイノリティ諸集団の歴史を概論するという趣旨のものなので、特別に目新しい知見はないのだが、現代（戦後）との比較において戦時中の在日コリアンの動員や強制連行の実態に言及している箇所がいくつかあり、quotableなので取り上げたい。

以下の2つの引用は、それぞれ、ニューカマー増加により多民族化した現代日本、戦前までは多民族帝国だった近代日本、ニューカマー増加で外国人労働者の編入という新しい問題に直面した現代日本といった――入門的文脈では頼らざるを得ない、しかしある意味で非常にミスリーディングな――ストーリーに留保を付すときに有用だろう。

:::{.callout-note}
## 戦時中の「多民族社会日本」？
- 「［引用者注: 戦時中に内地への朝鮮人労働者の大量の動員の結果として敗戦時にはおよそ200万人の在日朝鮮人と4万人の中国人が居住していたことについて］日本人人口が大部分であった日本列島にこのように異民族が大量に居住するようになっていたのは歴史上かつてないことであった。付言すれば、外国人居住者が増加し「多文化共生」を行政当局すらもスローガンとするようになった21世紀初頭に比べてもこの時の日本列島の異民族人口比率は高い水準にあった」（外村 2010: 200）
:::

:::{.callout-note}
## 「多民族」でも「単一民族」でもあった日本帝国
- 「確かに日本帝国は複数の民族をその内側に包容しており、多民族統合のイデオロギーが様々に語られたことは事実である。しかし日本人中心の社会に異民族が入り込むことを日本人民衆は望まなかったし、自分たちが主導する秩序の揺らぎに対しては過剰と言えるほどに警戒的であったのである。」（外村 2010: 221-222）
:::

:::{.callout-note}
## 「多民族」でも「単一民族」でもあった日本帝国
- 「…戦時期における朝鮮人労働者の日本内地への「移入」をめぐる議論や政策は、現代日本におけるいわゆる外国人労働者問題をめぐるそれと酷似している」（外村 2010: 222）
:::    

